// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// AuthSignupRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type AuthSignupRequest struct {
	Context UserContext `json:"context"`
	Method  *string     `json:"method"`
	Plan    string      `json:"plan,omitempty"`
}

// Validate returns field-level errors for the request, empty on success.
func (r AuthSignupRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.Method == nil {
		errs = append(errs, eventmap.FieldError{Field: "method", Message: "required"})
	} else if !validAuthSignupRequestMethod(*r.Method) {
		errs = append(errs, eventmap.FieldError{Field: "method", Message: "must be one of email | google | apple"})
	}
	return errs
}

var validAuthSignupRequestMethodSet = map[string]struct{}{
	"apple":  {},
	"email":  {},
	"google": {},
}

func validAuthSignupRequestMethod(s string) bool {
	_, ok := validAuthSignupRequestMethodSet[s]
	return ok
}
