// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// AuthLogoutRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type AuthLogoutRequest struct {
	Context         UserContext `json:"context"`
	DurationSeconds *int64      `json:"duration_seconds"`
}

// Validate returns field-level errors for the request, empty on success.
func (r AuthLogoutRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.DurationSeconds == nil {
		errs = append(errs, eventmap.FieldError{Field: "duration_seconds", Message: "required"})
	}
	return errs
}
