// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// AuthLoginRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type AuthLoginRequest struct {
	Context UserContext `json:"context"`
	Method  *string     `json:"method"`
	Success *bool       `json:"success"`
}

// Validate returns field-level errors for the request, empty on success.
func (r AuthLoginRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.Method == nil {
		errs = append(errs, eventmap.FieldError{Field: "method", Message: "required"})
	} else if !validAuthLoginRequestMethod(*r.Method) {
		errs = append(errs, eventmap.FieldError{Field: "method", Message: "must be one of email | google | apple"})
	}
	if r.Success == nil {
		errs = append(errs, eventmap.FieldError{Field: "success", Message: "required"})
	}
	return errs
}

var validAuthLoginRequestMethodSet = map[string]struct{}{
	"apple":  {},
	"email":  {},
	"google": {},
}

func validAuthLoginRequestMethod(s string) bool {
	_, ok := validAuthLoginRequestMethodSet[s]
	return ok
}
