// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// CartCheckoutRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type CartCheckoutRequest struct {
	Context       UserContext `json:"context"`
	CartID        *string     `json:"cart_id"`
	Currency      *string     `json:"currency"`
	ItemCount     *int64      `json:"item_count"`
	SubtotalCents *int64      `json:"subtotal_cents"`
}

// Validate returns field-level errors for the request, empty on success.
func (r CartCheckoutRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.CartID == nil {
		errs = append(errs, eventmap.FieldError{Field: "cart_id", Message: "required"})
	}
	if r.Currency == nil {
		errs = append(errs, eventmap.FieldError{Field: "currency", Message: "required"})
	} else if !validCartCheckoutRequestCurrency(*r.Currency) {
		errs = append(errs, eventmap.FieldError{Field: "currency", Message: "must be one of USD | EUR | GBP"})
	}
	if r.ItemCount == nil {
		errs = append(errs, eventmap.FieldError{Field: "item_count", Message: "required"})
	}
	if r.SubtotalCents == nil {
		errs = append(errs, eventmap.FieldError{Field: "subtotal_cents", Message: "required"})
	}
	return errs
}

var validCartCheckoutRequestCurrencySet = map[string]struct{}{
	"EUR": {},
	"GBP": {},
	"USD": {},
}

func validCartCheckoutRequestCurrency(s string) bool {
	_, ok := validCartCheckoutRequestCurrencySet[s]
	return ok
}
