// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// CartItemAddedRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type CartItemAddedRequest struct {
	Context  UserContext `json:"context"`
	CartID   *string     `json:"cart_id"`
	Quantity *int64      `json:"quantity"`
	SKU      *string     `json:"sku"`
}

// Validate returns field-level errors for the request, empty on success.
func (r CartItemAddedRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.CartID == nil {
		errs = append(errs, eventmap.FieldError{Field: "cart_id", Message: "required"})
	}
	if r.Quantity == nil {
		errs = append(errs, eventmap.FieldError{Field: "quantity", Message: "required"})
	}
	if r.SKU == nil {
		errs = append(errs, eventmap.FieldError{Field: "sku", Message: "required"})
	}
	return errs
}
