// Code generated by openevents. DO NOT EDIT.

package user

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// CartPurchaseRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type CartPurchaseRequest struct {
	Context       UserContext `json:"context"`
	CartID        *string     `json:"cart_id"`
	CouponCode    string      `json:"coupon_code,omitempty"`
	OrderID       *string     `json:"order_id"`
	PaymentMethod *string     `json:"payment_method"`
	TotalCents    *int64      `json:"total_cents"`
}

// Validate returns field-level errors for the request, empty on success.
func (r CartPurchaseRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.CartID == nil {
		errs = append(errs, eventmap.FieldError{Field: "cart_id", Message: "required"})
	}
	if r.OrderID == nil {
		errs = append(errs, eventmap.FieldError{Field: "order_id", Message: "required"})
	}
	if r.PaymentMethod == nil {
		errs = append(errs, eventmap.FieldError{Field: "payment_method", Message: "required"})
	} else if !validCartPurchaseRequestPaymentMethod(*r.PaymentMethod) {
		errs = append(errs, eventmap.FieldError{Field: "payment_method", Message: "must be one of card | apple_pay | google_pay"})
	}
	if r.TotalCents == nil {
		errs = append(errs, eventmap.FieldError{Field: "total_cents", Message: "required"})
	}
	return errs
}

var validCartPurchaseRequestPaymentMethodSet = map[string]struct{}{
	"apple_pay":  {},
	"card":       {},
	"google_pay": {},
}

func validCartPurchaseRequestPaymentMethod(s string) bool {
	_, ok := validCartPurchaseRequestPaymentMethodSet[s]
	return ok
}
