// Code generated by openevents. DO NOT EDIT.

package user

type UserContext struct {
	Platform  string `json:"platform"`
	SessionID string `json:"session_id,omitempty"`
	TenantID  string `json:"tenant_id"`
	UserID    string `json:"user_id,omitempty"`
}
