// Code generated by openevents. DO NOT EDIT.

package user

const (
	AuthLoginV1     = "user.auth.login@1"
	AuthLogoutV1    = "user.auth.logout@1"
	AuthSignupV1    = "user.auth.signup@1"
	CartCheckoutV1  = "user.cart.checkout@1"
	CartItemAddedV1 = "user.cart.item_added@1"
	CartPurchaseV1  = "user.cart.purchase@1"
)
