// Code generated by openevents. DO NOT EDIT.

package device

type DeviceContext struct {
	DeviceID        string `json:"device_id"`
	FirmwareVersion string `json:"firmware_version,omitempty"`
	SerialNumber    string `json:"serial_number,omitempty"`
	TenantID        string `json:"tenant_id"`
}
