// Code generated by openevents. DO NOT EDIT.

package device

import (
	"fmt"

	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// DiagnosticsStackUsageRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type DiagnosticsStackUsageRequest struct {
	Context             DeviceContext    `json:"context"`
	HighestUsagePercent *int64           `json:"highest_usage_percent"`
	HighestUsageThread  *string          `json:"highest_usage_thread"`
	ThreadCount         *int64           `json:"thread_count"`
	Threads             []*ThreadRequest `json:"threads"`
}

// ThreadRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type ThreadRequest struct {
	Name           *string `json:"name"`
	Priority       *int64  `json:"priority"`
	StackSizeBytes *int64  `json:"stack_size_bytes"`
	StackUsedBytes *int64  `json:"stack_used_bytes"`
	State          *string `json:"state"`
	UsagePercent   *int64  `json:"usage_percent"`
}

// Validate returns field-level errors for the request, empty on success.
func (r DiagnosticsStackUsageRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.HighestUsagePercent == nil {
		errs = append(errs, eventmap.FieldError{Field: "highest_usage_percent", Message: "required"})
	}
	if r.HighestUsageThread == nil {
		errs = append(errs, eventmap.FieldError{Field: "highest_usage_thread", Message: "required"})
	}
	if r.ThreadCount == nil {
		errs = append(errs, eventmap.FieldError{Field: "thread_count", Message: "required"})
	}
	if r.Threads == nil {
		errs = append(errs, eventmap.FieldError{Field: "threads", Message: "required"})
	} else {
		for i, elem := range r.Threads {
			elemPath := fmt.Sprintf("%s[%d]", "threads", i)
			if elem == nil {
				errs = append(errs, eventmap.FieldError{Field: elemPath, Message: "required"})
			} else {
				errs = append(errs, elem.Validate(elemPath)...)
			}
		}
	}
	return errs
}

// Validate returns field-level errors for ThreadRequest under prefix, empty on success.
func (r *ThreadRequest) Validate(prefix string) []eventmap.FieldError {
	if r == nil {
		return nil
	}
	var errs []eventmap.FieldError
	if r.Name == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".name", Message: "required"})
	}
	if r.Priority == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".priority", Message: "required"})
	}
	if r.StackSizeBytes == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".stack_size_bytes", Message: "required"})
	}
	if r.StackUsedBytes == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".stack_used_bytes", Message: "required"})
	}
	if r.State == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".state", Message: "required"})
	} else if !validThreadRequestState(*r.State) {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".state", Message: "must be one of running | ready | pending | suspended | dead"})
	}
	if r.UsagePercent == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".usage_percent", Message: "required"})
	}
	return errs
}

var validThreadRequestStateSet = map[string]struct{}{
	"dead":      {},
	"pending":   {},
	"ready":     {},
	"running":   {},
	"suspended": {},
}

func validThreadRequestState(s string) bool {
	_, ok := validThreadRequestStateSet[s]
	return ok
}
