// Code generated by openevents. DO NOT EDIT.

package device

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// IncidentTemperatureRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type IncidentTemperatureRequest struct {
	Context    DeviceContext `json:"context"`
	BreachType *string       `json:"breach_type"`
	DegreesC   *float64      `json:"degrees_c"`
	ThresholdC *float64      `json:"threshold_c"`
}

// Validate returns field-level errors for the request, empty on success.
func (r IncidentTemperatureRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.BreachType == nil {
		errs = append(errs, eventmap.FieldError{Field: "breach_type", Message: "required"})
	} else if !validIncidentTemperatureRequestBreachType(*r.BreachType) {
		errs = append(errs, eventmap.FieldError{Field: "breach_type", Message: "must be one of over | under"})
	}
	if r.DegreesC == nil {
		errs = append(errs, eventmap.FieldError{Field: "degrees_c", Message: "required"})
	}
	if r.ThresholdC == nil {
		errs = append(errs, eventmap.FieldError{Field: "threshold_c", Message: "required"})
	}
	return errs
}

var validIncidentTemperatureRequestBreachTypeSet = map[string]struct{}{
	"over":  {},
	"under": {},
}

func validIncidentTemperatureRequestBreachType(s string) bool {
	_, ok := validIncidentTemperatureRequestBreachTypeSet[s]
	return ok
}
