// Code generated by openevents. DO NOT EDIT.

package device

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// IncidentDropRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type IncidentDropRequest struct {
	Context           DeviceContext `json:"context"`
	Axis              *string       `json:"axis"`
	DurationMs        *int64        `json:"duration_ms"`
	PeakAccelerationG *float64      `json:"peak_acceleration_g"`
}

// Validate returns field-level errors for the request, empty on success.
func (r IncidentDropRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.Axis == nil {
		errs = append(errs, eventmap.FieldError{Field: "axis", Message: "required"})
	} else if !validIncidentDropRequestAxis(*r.Axis) {
		errs = append(errs, eventmap.FieldError{Field: "axis", Message: "must be one of x | y | z"})
	}
	if r.DurationMs == nil {
		errs = append(errs, eventmap.FieldError{Field: "duration_ms", Message: "required"})
	}
	if r.PeakAccelerationG == nil {
		errs = append(errs, eventmap.FieldError{Field: "peak_acceleration_g", Message: "required"})
	}
	return errs
}

var validIncidentDropRequestAxisSet = map[string]struct{}{
	"x": {},
	"y": {},
	"z": {},
}

func validIncidentDropRequestAxis(s string) bool {
	_, ok := validIncidentDropRequestAxisSet[s]
	return ok
}
