// Code generated by openevents. DO NOT EDIT.

package device

import (
	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// InfoSoftwareRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type InfoSoftwareRequest struct {
	Context                       DeviceContext    `json:"context"`
	PcbaHwManufacturedTimestampMs *int64           `json:"pcba_hw_manufactured_timestamp_ms"`
	PcbaHwVersion                 *string          `json:"pcba_hw_version"`
	ProductType                   *string          `json:"product_type"`
	SerialNumber                  *string          `json:"serial_number"`
	UniqueID                      *int64           `json:"unique_id"`
	Versions                      *VersionsRequest `json:"versions"`
}

// VersionsRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type VersionsRequest struct {
	AppGitSha                *string `json:"app_git_sha"`
	AppSemanticVersion       *string `json:"app_semantic_version"`
	BootloaderBuildTimestamp *int64  `json:"bootloader_build_timestamp"`
	BootloaderGitSha         *string `json:"bootloader_git_sha"`
	BuildType                *string `json:"build_type"`
	CompileTime              *string `json:"compile_time"`
	CompiledBy               *string `json:"compiled_by"`
	CompiledOnOS             *string `json:"compiled_on_os"`
	CompilerVersion          *string `json:"compiler_version"`
	HwPlatform               *string `json:"hw_platform"`
	ZephyrKernelGitSha       *string `json:"zephyr_kernel_git_sha"`
	ZephyrKernelVersion      *string `json:"zephyr_kernel_version"`
}

// Validate returns field-level errors for the request, empty on success.
func (r InfoSoftwareRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.PcbaHwManufacturedTimestampMs == nil {
		errs = append(errs, eventmap.FieldError{Field: "pcba_hw_manufactured_timestamp_ms", Message: "required"})
	}
	if r.PcbaHwVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: "pcba_hw_version", Message: "required"})
	}
	if r.ProductType == nil {
		errs = append(errs, eventmap.FieldError{Field: "product_type", Message: "required"})
	}
	if r.SerialNumber == nil {
		errs = append(errs, eventmap.FieldError{Field: "serial_number", Message: "required"})
	}
	if r.UniqueID == nil {
		errs = append(errs, eventmap.FieldError{Field: "unique_id", Message: "required"})
	}
	if r.Versions == nil {
		errs = append(errs, eventmap.FieldError{Field: "versions", Message: "required"})
	} else {
		errs = append(errs, r.Versions.Validate("versions")...)
	}
	return errs
}

// Validate returns field-level errors for VersionsRequest under prefix, empty on success.
func (r *VersionsRequest) Validate(prefix string) []eventmap.FieldError {
	if r == nil {
		return nil
	}
	var errs []eventmap.FieldError
	if r.AppGitSha == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".app_git_sha", Message: "required"})
	}
	if r.AppSemanticVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".app_semantic_version", Message: "required"})
	}
	if r.BootloaderBuildTimestamp == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".bootloader_build_timestamp", Message: "required"})
	}
	if r.BootloaderGitSha == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".bootloader_git_sha", Message: "required"})
	}
	if r.BuildType == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".build_type", Message: "required"})
	}
	if r.CompileTime == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".compile_time", Message: "required"})
	}
	if r.CompiledBy == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".compiled_by", Message: "required"})
	}
	if r.CompiledOnOS == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".compiled_on_os", Message: "required"})
	}
	if r.CompilerVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".compiler_version", Message: "required"})
	}
	if r.HwPlatform == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".hw_platform", Message: "required"})
	}
	if r.ZephyrKernelGitSha == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".zephyr_kernel_git_sha", Message: "required"})
	}
	if r.ZephyrKernelVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".zephyr_kernel_version", Message: "required"})
	}
	return errs
}
