// Code generated by openevents. DO NOT EDIT.

package device

import (
	"time"

	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// InfoHardwareRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type InfoHardwareRequest struct {
	Context                DeviceContext               `json:"context"`
	EepromFormatVersion    *EepromFormatVersionRequest `json:"eeprom_format_version"`
	FuelCellLotNumber      string                      `json:"fuel_cell_lot_number,omitempty"`
	FuelCellVendor         string                      `json:"fuel_cell_vendor,omitempty"`
	ManufacturingTimestamp *string                     `json:"manufacturing_timestamp"`
	ModulePcbVersion       *ModulePcbVersionRequest    `json:"module_pcb_version"`
	SensorType             *string                     `json:"sensor_type"`
	UniqueID               *string                     `json:"unique_id"`
}

// EepromFormatVersionRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type EepromFormatVersionRequest struct {
	Major *int64 `json:"major"`
	Minor *int64 `json:"minor"`
}

// ModulePcbVersionRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type ModulePcbVersionRequest struct {
	Major *int64 `json:"major"`
	Minor *int64 `json:"minor"`
}

// Validate returns field-level errors for the request, empty on success.
func (r InfoHardwareRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.EepromFormatVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: "eeprom_format_version", Message: "required"})
	} else {
		errs = append(errs, r.EepromFormatVersion.Validate("eeprom_format_version")...)
	}
	if r.ManufacturingTimestamp == nil {
		errs = append(errs, eventmap.FieldError{Field: "manufacturing_timestamp", Message: "required"})
	} else if _, err := time.Parse(time.RFC3339, *r.ManufacturingTimestamp); err != nil {
		errs = append(errs, eventmap.FieldError{Field: "manufacturing_timestamp", Message: "must be RFC3339 timestamp"})
	}
	if r.ModulePcbVersion == nil {
		errs = append(errs, eventmap.FieldError{Field: "module_pcb_version", Message: "required"})
	} else {
		errs = append(errs, r.ModulePcbVersion.Validate("module_pcb_version")...)
	}
	if r.SensorType == nil {
		errs = append(errs, eventmap.FieldError{Field: "sensor_type", Message: "required"})
	} else if !validInfoHardwareRequestSensorType(*r.SensorType) {
		errs = append(errs, eventmap.FieldError{Field: "sensor_type", Message: "must be one of unspecified | co | alcohol | oxygen | fuel_cell"})
	}
	if r.UniqueID == nil {
		errs = append(errs, eventmap.FieldError{Field: "unique_id", Message: "required"})
	}
	return errs
}

// Validate returns field-level errors for EepromFormatVersionRequest under prefix, empty on success.
func (r *EepromFormatVersionRequest) Validate(prefix string) []eventmap.FieldError {
	if r == nil {
		return nil
	}
	var errs []eventmap.FieldError
	if r.Major == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".major", Message: "required"})
	}
	if r.Minor == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".minor", Message: "required"})
	}
	return errs
}

// Validate returns field-level errors for ModulePcbVersionRequest under prefix, empty on success.
func (r *ModulePcbVersionRequest) Validate(prefix string) []eventmap.FieldError {
	if r == nil {
		return nil
	}
	var errs []eventmap.FieldError
	if r.Major == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".major", Message: "required"})
	}
	if r.Minor == nil {
		errs = append(errs, eventmap.FieldError{Field: prefix + ".minor", Message: "required"})
	}
	return errs
}

var validInfoHardwareRequestSensorTypeSet = map[string]struct{}{
	"alcohol":     {},
	"co":          {},
	"fuel_cell":   {},
	"oxygen":      {},
	"unspecified": {},
}

func validInfoHardwareRequestSensorType(s string) bool {
	_, ok := validInfoHardwareRequestSensorTypeSet[s]
	return ok
}
