// Code generated by openevents. DO NOT EDIT.

package device

import (
	"time"

	"github.com/sentiolabs/open-events/examples/demo/services/api/eventmap"
)

// InfoCalibrationRequest is the JSON body shape for this request.
// Required primitive fields use pointer types so the validator can
// distinguish "field omitted from JSON" from "field set to its zero value".
type InfoCalibrationRequest struct {
	Context       DeviceContext `json:"context"`
	Concentration *float64      `json:"concentration"`
	Integral      *int64        `json:"integral"`
	Timestamp     *string       `json:"timestamp"`
}

// Validate returns field-level errors for the request, empty on success.
func (r InfoCalibrationRequest) Validate() []eventmap.FieldError {
	errs := validateContext(r.Context)
	if r.Concentration == nil {
		errs = append(errs, eventmap.FieldError{Field: "concentration", Message: "required"})
	}
	if r.Integral == nil {
		errs = append(errs, eventmap.FieldError{Field: "integral", Message: "required"})
	}
	if r.Timestamp == nil {
		errs = append(errs, eventmap.FieldError{Field: "timestamp", Message: "required"})
	} else if _, err := time.Parse(time.RFC3339, *r.Timestamp); err != nil {
		errs = append(errs, eventmap.FieldError{Field: "timestamp", Message: "must be RFC3339 timestamp"})
	}
	return errs
}
