package python

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sentiolabs/open-events/internal/registry"
	"github.com/sentiolabs/open-events/internal/schemair"
)

const generatedHeader = "# Code generated by openevents. DO NOT EDIT."

// Emit writes per-domain Python bindings under cfg.Out for the given registry and lock.
// For each domain it produces:
//   - <cfg.Out>/event_names/<domain>.py  — one UPPER_SNAKE constant per event
//   - <cfg.Out>/context/<domain>.py      — <DomainPascal>Context @dataclass
//
// It also writes empty __init__.py files in event_names/ and context/.
func Emit(reg registry.Registry, lock schemair.Lock, cfg Config) error {
	bundles := schemair.GroupByDomain(reg)

	// Create event_names and context subdirectory __init__.py files.
	for _, subpkg := range []string{"event_names", "context"} {
		dir := filepath.Join(cfg.Out, subpkg)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %q: %w", dir, err)
		}
		if err := writeFile(filepath.Join(dir, "__init__.py"), ""); err != nil {
			return err
		}
	}

	for _, b := range bundles {
		if err := writeEventNames(cfg.Out, b); err != nil {
			return err
		}
		if err := writeContext(cfg.Out, b); err != nil {
			return err
		}
	}
	return nil
}

// writeEventNames emits event_names/<domain>.py.
func writeEventNames(outDir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name

	// Sort events for determinism.
	events := append([]registry.Event(nil), b.Events...)
	sort.Slice(events, func(i, j int) bool {
		return wireKey(events[i]) < wireKey(events[j])
	})

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n")

	for _, ev := range events {
		ident := eventConstName(ev, domainName)
		wire := wireKey(ev)
		fmt.Fprintf(&sb, "%s = %q\n", ident, wire)
	}

	dir := filepath.Join(outDir, "event_names")
	return writeFile(filepath.Join(dir, domainName+".py"), sb.String())
}

// writeContext emits context/<domain>.py.
func writeContext(outDir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name
	className := pascalCase(domainName) + "Context"

	// Sort context fields for determinism: required fields first, then optional,
	// both groups sorted alphabetically. This ensures @dataclass fields with defaults
	// come after fields without defaults.
	type namedField struct {
		name  string
		field registry.Field
	}
	fields := make([]namedField, 0, len(b.Domain.Context))
	for name, f := range b.Domain.Context {
		fields = append(fields, namedField{name: name, field: f})
	}
	// Sort required before optional, then alphabetically within each group.
	sort.Slice(fields, func(i, j int) bool {
		ri, rj := fields[i].field.Required, fields[j].field.Required
		if ri != rj {
			return ri // required fields first
		}
		return fields[i].name < fields[j].name
	})

	// Determine if any optional fields exist (need Optional import).
	hasOptional := false
	for _, nf := range fields {
		if !nf.field.Required {
			hasOptional = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n")
	sb.WriteString("from dataclasses import dataclass\n")
	if hasOptional {
		sb.WriteString("from typing import Optional\n")
	}
	sb.WriteString("\n\n")
	sb.WriteString("@dataclass\n")
	fmt.Fprintf(&sb, "class %s:\n", className)

	if len(fields) == 0 {
		sb.WriteString("    pass\n")
	} else {
		for _, nf := range fields {
			pyType := fieldPyType(nf.field)
			if nf.field.Required {
				fmt.Fprintf(&sb, "    %s: %s\n", nf.name, pyType)
			} else {
				fmt.Fprintf(&sb, "    %s: Optional[%s] = None\n", nf.name, pyType)
			}
		}
	}

	dir := filepath.Join(outDir, "context")
	return writeFile(filepath.Join(dir, domainName+".py"), sb.String())
}

func writeFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %q: %w", path, err)
	}
	return nil
}

// wireKey returns "<name>@<version>".
func wireKey(ev registry.Event) string {
	return fmt.Sprintf("%s@%d", ev.Name, ev.Version)
}

// eventConstName derives the Python constant name for an event, dropping the domain
// prefix and appending _V<version>. E.g. "user.auth.signup@1" in domain "user"
// becomes "AUTH_SIGNUP_V1".
func eventConstName(ev registry.Event, domain string) string {
	parts := strings.Split(ev.Name, ".")
	if len(parts) > 0 && parts[0] == domain {
		parts = parts[1:]
	}
	// Join parts, splitting each on underscores/hyphens, then uppercase all.
	var segments []string
	for _, p := range parts {
		p = strings.ReplaceAll(p, "-", "_")
		for _, sub := range strings.Split(p, "_") {
			if sub != "" {
				segments = append(segments, strings.ToUpper(sub))
			}
		}
	}
	return strings.Join(segments, "_") + fmt.Sprintf("_V%d", ev.Version)
}

// pascalCase converts a domain name to PascalCase. E.g. "user" → "User".
func pascalCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// fieldPyType maps a registry FieldType to a Python type annotation string.
func fieldPyType(f registry.Field) string {
	switch f.Type {
	case registry.FieldTypeString:
		return "str"
	case registry.FieldTypeInteger:
		return "int"
	case registry.FieldTypeNumber:
		return "float"
	case registry.FieldTypeBoolean:
		return "bool"
	case registry.FieldTypeTimestamp:
		return "str"
	case registry.FieldTypeDate:
		return "str"
	case registry.FieldTypeUUID:
		return "str"
	case registry.FieldTypeEnum:
		return "str"
	case registry.FieldTypeArray:
		return "list"
	case registry.FieldTypeObject:
		return "dict"
	default:
		return "object"
	}
}
