package python_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sentiolabs/open-events/internal/codegen/codegentest"
	python "github.com/sentiolabs/open-events/internal/codegen/python"
	"github.com/sentiolabs/open-events/internal/registry"
	"github.com/sentiolabs/open-events/internal/schemair"
)

// buildTestRegistry returns the shared 2-domain fixture with an optional
// user_id context field; the Python emitter relies on the optional field to
// exercise the X | None / Optional[...] code path.
func buildTestRegistry(t *testing.T) (registry.Registry, schemair.Lock) {
	return codegentest.TwoDomainRegistry(t, codegentest.TwoDomainOptions{IncludeUserID: true})
}

func TestEmit_CreatesExpectedFiles(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := python.Config{Out: outDir, Package: "acme.events"}
	if err := python.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "event_names", "__init__.py"),
		filepath.Join(outDir, "event_names", "user.py"),
		filepath.Join(outDir, "event_names", "device.py"),
		filepath.Join(outDir, "context", "__init__.py"),
		filepath.Join(outDir, "context", "user.py"),
		filepath.Join(outDir, "context", "device.py"),
	}

	for _, path := range expectedFiles {
		if _, err := os.Stat(path); err != nil {
			t.Errorf("expected file %s to exist: %v", path, err)
		}
	}
}

func TestEmit_EventNamesContent(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := python.Config{Out: outDir, Package: "acme.events"}
	if err := python.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	// user domain: user.auth.signup@1 → drop domain "user" → auth.signup → AUTH_SIGNUP_V1
	userNames, err := os.ReadFile(filepath.Join(outDir, "event_names", "user.py"))
	if err != nil {
		t.Fatalf("read event_names/user.py: %v", err)
	}
	userText := string(userNames)

	if !strings.HasPrefix(userText, "# Code generated by openevents. DO NOT EDIT.") {
		t.Errorf("event_names/user.py missing generated header:\n%s", userText)
	}
	if !strings.Contains(userText, `AUTH_SIGNUP_V1`) {
		t.Errorf("event_names/user.py missing AUTH_SIGNUP_V1 constant:\n%s", userText)
	}
	if !strings.Contains(userText, `"user.auth.signup@1"`) {
		t.Errorf("event_names/user.py missing wire value:\n%s", userText)
	}

	// device domain: device.info.hardware@1 → drop "device" → info.hardware → INFO_HARDWARE_V1
	deviceNames, err := os.ReadFile(filepath.Join(outDir, "event_names", "device.py"))
	if err != nil {
		t.Fatalf("read event_names/device.py: %v", err)
	}
	deviceText := string(deviceNames)

	if !strings.Contains(deviceText, `INFO_HARDWARE_V1`) {
		t.Errorf("event_names/device.py missing INFO_HARDWARE_V1 constant:\n%s", deviceText)
	}
	if !strings.Contains(deviceText, `"device.info.hardware@1"`) {
		t.Errorf("event_names/device.py missing wire value:\n%s", deviceText)
	}
}

func TestEmit_ContextContent(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := python.Config{Out: outDir, Package: "acme.events"}
	if err := python.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	// user domain: UserContext with tenant_id (required) and user_id (optional)
	userCtx, err := os.ReadFile(filepath.Join(outDir, "context", "user.py"))
	if err != nil {
		t.Fatalf("read context/user.py: %v", err)
	}
	userText := string(userCtx)

	if !strings.HasPrefix(userText, "# Code generated by openevents. DO NOT EDIT.") {
		t.Errorf("context/user.py missing generated header:\n%s", userText)
	}
	if !strings.Contains(userText, "from dataclasses import dataclass") {
		t.Errorf("context/user.py missing dataclass import:\n%s", userText)
	}
	if !strings.Contains(userText, "from typing import Optional") {
		t.Errorf("context/user.py missing Optional import:\n%s", userText)
	}
	if !strings.Contains(userText, "@dataclass") {
		t.Errorf("context/user.py missing @dataclass decorator:\n%s", userText)
	}
	if !strings.Contains(userText, "class UserContext:") {
		t.Errorf("context/user.py missing UserContext class:\n%s", userText)
	}
	if !strings.Contains(userText, "tenant_id: str") {
		t.Errorf("context/user.py missing required tenant_id field:\n%s", userText)
	}
	// Optional field: user_id should have Optional[str] = None
	if !strings.Contains(userText, "user_id: Optional[str] = None") {
		t.Errorf("context/user.py missing optional user_id field:\n%s", userText)
	}

	// device domain: DeviceContext with device_id (required)
	deviceCtx, err := os.ReadFile(filepath.Join(outDir, "context", "device.py"))
	if err != nil {
		t.Fatalf("read context/device.py: %v", err)
	}
	deviceText := string(deviceCtx)

	if !strings.Contains(deviceText, "class DeviceContext:") {
		t.Errorf("context/device.py missing DeviceContext class:\n%s", deviceText)
	}
	if !strings.Contains(deviceText, "device_id: str") {
		t.Errorf("context/device.py missing required device_id field:\n%s", deviceText)
	}
}

func TestEmit_InitFilesAreEmpty(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := python.Config{Out: outDir, Package: "acme.events"}
	if err := python.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	for _, rel := range []string{
		filepath.Join("event_names", "__init__.py"),
		filepath.Join("context", "__init__.py"),
	} {
		data, err := os.ReadFile(filepath.Join(outDir, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		if len(strings.TrimSpace(string(data))) != 0 {
			t.Errorf("%s must be empty, got:\n%s", rel, string(data))
		}
	}
}

func TestEmit_GeneratedFileHeader(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := python.Config{Out: outDir, Package: "acme.events"}
	if err := python.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	// Non-init files must start with the generated header.
	for _, rel := range []string{
		filepath.Join("event_names", "user.py"),
		filepath.Join("event_names", "device.py"),
		filepath.Join("context", "user.py"),
		filepath.Join("context", "device.py"),
	} {
		data, err := os.ReadFile(filepath.Join(outDir, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		if !strings.HasPrefix(string(data), "# Code generated by openevents. DO NOT EDIT.") {
			t.Errorf("%s must start with generated header, got:\n%s", rel, string(data[:min(len(data), 80)]))
		}
	}
}
