// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: com/acme/platform/device/v1/events.proto

package device

import (
	common "github.com/sentiolabs/open-events/examples/demo/services/api/eventmap/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceDiagnosticsStackUsageV1Properties_Threads_State int32

const (
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_UNSPECIFIED DeviceDiagnosticsStackUsageV1Properties_Threads_State = 0
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_RUNNING     DeviceDiagnosticsStackUsageV1Properties_Threads_State = 1
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_READY       DeviceDiagnosticsStackUsageV1Properties_Threads_State = 2
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_PENDING     DeviceDiagnosticsStackUsageV1Properties_Threads_State = 3
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_SUSPENDED   DeviceDiagnosticsStackUsageV1Properties_Threads_State = 4
	DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_DEAD        DeviceDiagnosticsStackUsageV1Properties_Threads_State = 5
)

// Enum value maps for DeviceDiagnosticsStackUsageV1Properties_Threads_State.
var (
	DeviceDiagnosticsStackUsageV1Properties_Threads_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_RUNNING",
		2: "STATE_READY",
		3: "STATE_PENDING",
		4: "STATE_SUSPENDED",
		5: "STATE_DEAD",
	}
	DeviceDiagnosticsStackUsageV1Properties_Threads_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_RUNNING":     1,
		"STATE_READY":       2,
		"STATE_PENDING":     3,
		"STATE_SUSPENDED":   4,
		"STATE_DEAD":        5,
	}
)

func (x DeviceDiagnosticsStackUsageV1Properties_Threads_State) Enum() *DeviceDiagnosticsStackUsageV1Properties_Threads_State {
	p := new(DeviceDiagnosticsStackUsageV1Properties_Threads_State)
	*p = x
	return p
}

func (x DeviceDiagnosticsStackUsageV1Properties_Threads_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceDiagnosticsStackUsageV1Properties_Threads_State) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_device_v1_events_proto_enumTypes[0].Descriptor()
}

func (DeviceDiagnosticsStackUsageV1Properties_Threads_State) Type() protoreflect.EnumType {
	return &file_com_acme_platform_device_v1_events_proto_enumTypes[0]
}

func (x DeviceDiagnosticsStackUsageV1Properties_Threads_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceDiagnosticsStackUsageV1Properties_Threads_State.Descriptor instead.
func (DeviceDiagnosticsStackUsageV1Properties_Threads_State) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{2, 0, 0}
}

type DeviceIncidentDropV1Properties_Axis int32

const (
	DeviceIncidentDropV1Properties_AXIS_UNSPECIFIED DeviceIncidentDropV1Properties_Axis = 0
	DeviceIncidentDropV1Properties_AXIS_X           DeviceIncidentDropV1Properties_Axis = 1
	DeviceIncidentDropV1Properties_AXIS_Y           DeviceIncidentDropV1Properties_Axis = 2
	DeviceIncidentDropV1Properties_AXIS_Z           DeviceIncidentDropV1Properties_Axis = 3
)

// Enum value maps for DeviceIncidentDropV1Properties_Axis.
var (
	DeviceIncidentDropV1Properties_Axis_name = map[int32]string{
		0: "AXIS_UNSPECIFIED",
		1: "AXIS_X",
		2: "AXIS_Y",
		3: "AXIS_Z",
	}
	DeviceIncidentDropV1Properties_Axis_value = map[string]int32{
		"AXIS_UNSPECIFIED": 0,
		"AXIS_X":           1,
		"AXIS_Y":           2,
		"AXIS_Z":           3,
	}
)

func (x DeviceIncidentDropV1Properties_Axis) Enum() *DeviceIncidentDropV1Properties_Axis {
	p := new(DeviceIncidentDropV1Properties_Axis)
	*p = x
	return p
}

func (x DeviceIncidentDropV1Properties_Axis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceIncidentDropV1Properties_Axis) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_device_v1_events_proto_enumTypes[1].Descriptor()
}

func (DeviceIncidentDropV1Properties_Axis) Type() protoreflect.EnumType {
	return &file_com_acme_platform_device_v1_events_proto_enumTypes[1]
}

func (x DeviceIncidentDropV1Properties_Axis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceIncidentDropV1Properties_Axis.Descriptor instead.
func (DeviceIncidentDropV1Properties_Axis) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{4, 0}
}

type DeviceIncidentTemperatureV1Properties_BreachType int32

const (
	DeviceIncidentTemperatureV1Properties_BREACH_TYPE_UNSPECIFIED DeviceIncidentTemperatureV1Properties_BreachType = 0
	DeviceIncidentTemperatureV1Properties_BREACH_TYPE_OVER        DeviceIncidentTemperatureV1Properties_BreachType = 1
	DeviceIncidentTemperatureV1Properties_BREACH_TYPE_UNDER       DeviceIncidentTemperatureV1Properties_BreachType = 2
)

// Enum value maps for DeviceIncidentTemperatureV1Properties_BreachType.
var (
	DeviceIncidentTemperatureV1Properties_BreachType_name = map[int32]string{
		0: "BREACH_TYPE_UNSPECIFIED",
		1: "BREACH_TYPE_OVER",
		2: "BREACH_TYPE_UNDER",
	}
	DeviceIncidentTemperatureV1Properties_BreachType_value = map[string]int32{
		"BREACH_TYPE_UNSPECIFIED": 0,
		"BREACH_TYPE_OVER":        1,
		"BREACH_TYPE_UNDER":       2,
	}
)

func (x DeviceIncidentTemperatureV1Properties_BreachType) Enum() *DeviceIncidentTemperatureV1Properties_BreachType {
	p := new(DeviceIncidentTemperatureV1Properties_BreachType)
	*p = x
	return p
}

func (x DeviceIncidentTemperatureV1Properties_BreachType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceIncidentTemperatureV1Properties_BreachType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_device_v1_events_proto_enumTypes[2].Descriptor()
}

func (DeviceIncidentTemperatureV1Properties_BreachType) Type() protoreflect.EnumType {
	return &file_com_acme_platform_device_v1_events_proto_enumTypes[2]
}

func (x DeviceIncidentTemperatureV1Properties_BreachType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceIncidentTemperatureV1Properties_BreachType.Descriptor instead.
func (DeviceIncidentTemperatureV1Properties_BreachType) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{6, 0}
}

type DeviceInfoHardwareV1Properties_SensorType int32

const (
	DeviceInfoHardwareV1Properties_SENSOR_TYPE_UNSPECIFIED DeviceInfoHardwareV1Properties_SensorType = 0
	DeviceInfoHardwareV1Properties_SENSOR_TYPE_CO          DeviceInfoHardwareV1Properties_SensorType = 1
	DeviceInfoHardwareV1Properties_SENSOR_TYPE_ALCOHOL     DeviceInfoHardwareV1Properties_SensorType = 2
	DeviceInfoHardwareV1Properties_SENSOR_TYPE_OXYGEN      DeviceInfoHardwareV1Properties_SensorType = 3
	DeviceInfoHardwareV1Properties_SENSOR_TYPE_FUEL_CELL   DeviceInfoHardwareV1Properties_SensorType = 4
)

// Enum value maps for DeviceInfoHardwareV1Properties_SensorType.
var (
	DeviceInfoHardwareV1Properties_SensorType_name = map[int32]string{
		0: "SENSOR_TYPE_UNSPECIFIED",
		1: "SENSOR_TYPE_CO",
		2: "SENSOR_TYPE_ALCOHOL",
		3: "SENSOR_TYPE_OXYGEN",
		4: "SENSOR_TYPE_FUEL_CELL",
	}
	DeviceInfoHardwareV1Properties_SensorType_value = map[string]int32{
		"SENSOR_TYPE_UNSPECIFIED": 0,
		"SENSOR_TYPE_CO":          1,
		"SENSOR_TYPE_ALCOHOL":     2,
		"SENSOR_TYPE_OXYGEN":      3,
		"SENSOR_TYPE_FUEL_CELL":   4,
	}
)

func (x DeviceInfoHardwareV1Properties_SensorType) Enum() *DeviceInfoHardwareV1Properties_SensorType {
	p := new(DeviceInfoHardwareV1Properties_SensorType)
	*p = x
	return p
}

func (x DeviceInfoHardwareV1Properties_SensorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceInfoHardwareV1Properties_SensorType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_device_v1_events_proto_enumTypes[3].Descriptor()
}

func (DeviceInfoHardwareV1Properties_SensorType) Type() protoreflect.EnumType {
	return &file_com_acme_platform_device_v1_events_proto_enumTypes[3]
}

func (x DeviceInfoHardwareV1Properties_SensorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceInfoHardwareV1Properties_SensorType.Descriptor instead.
func (DeviceInfoHardwareV1Properties_SensorType) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{10, 0}
}

type DeviceContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        *string                `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
	FirmwareVersion *string                `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3,oneof" json:"firmware_version,omitempty"`
	SerialNumber    *string                `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	TenantId        *string                `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceContext) Reset() {
	*x = DeviceContext{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceContext) ProtoMessage() {}

func (x *DeviceContext) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceContext.ProtoReflect.Descriptor instead.
func (*DeviceContext) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceContext) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *DeviceContext) GetFirmwareVersion() string {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return ""
}

func (x *DeviceContext) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *DeviceContext) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

// Per-thread RTOS stack usage snapshot from the device.
type DeviceDiagnosticsStackUsageV1 struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	EventName     string                                   `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                                    `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                                   `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp                   `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                           `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                           `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceDiagnosticsStackUsageV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDiagnosticsStackUsageV1) Reset() {
	*x = DeviceDiagnosticsStackUsageV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDiagnosticsStackUsageV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDiagnosticsStackUsageV1) ProtoMessage() {}

func (x *DeviceDiagnosticsStackUsageV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDiagnosticsStackUsageV1.ProtoReflect.Descriptor instead.
func (*DeviceDiagnosticsStackUsageV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceDiagnosticsStackUsageV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceDiagnosticsStackUsageV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceDiagnosticsStackUsageV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceDiagnosticsStackUsageV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceDiagnosticsStackUsageV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceDiagnosticsStackUsageV1) GetProperties() *DeviceDiagnosticsStackUsageV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceDiagnosticsStackUsageV1Properties struct {
	state               protoimpl.MessageState                             `protogen:"open.v1"`
	HighestUsagePercent *int64                                             `protobuf:"varint,1,opt,name=highest_usage_percent,json=highestUsagePercent,proto3,oneof" json:"highest_usage_percent,omitempty"`
	HighestUsageThread  *string                                            `protobuf:"bytes,2,opt,name=highest_usage_thread,json=highestUsageThread,proto3,oneof" json:"highest_usage_thread,omitempty"`
	ThreadCount         *int64                                             `protobuf:"varint,3,opt,name=thread_count,json=threadCount,proto3,oneof" json:"thread_count,omitempty"`
	Threads             []*DeviceDiagnosticsStackUsageV1Properties_Threads `protobuf:"bytes,4,rep,name=threads,proto3" json:"threads,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeviceDiagnosticsStackUsageV1Properties) Reset() {
	*x = DeviceDiagnosticsStackUsageV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDiagnosticsStackUsageV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDiagnosticsStackUsageV1Properties) ProtoMessage() {}

func (x *DeviceDiagnosticsStackUsageV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDiagnosticsStackUsageV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceDiagnosticsStackUsageV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceDiagnosticsStackUsageV1Properties) GetHighestUsagePercent() int64 {
	if x != nil && x.HighestUsagePercent != nil {
		return *x.HighestUsagePercent
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1Properties) GetHighestUsageThread() string {
	if x != nil && x.HighestUsageThread != nil {
		return *x.HighestUsageThread
	}
	return ""
}

func (x *DeviceDiagnosticsStackUsageV1Properties) GetThreadCount() int64 {
	if x != nil && x.ThreadCount != nil {
		return *x.ThreadCount
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1Properties) GetThreads() []*DeviceDiagnosticsStackUsageV1Properties_Threads {
	if x != nil {
		return x.Threads
	}
	return nil
}

// Device experienced a drop event detected by accelerometer.
type DeviceIncidentDropV1 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	EventName     string                          `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                           `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                          `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp          `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                  `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                  `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceIncidentDropV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIncidentDropV1) Reset() {
	*x = DeviceIncidentDropV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIncidentDropV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIncidentDropV1) ProtoMessage() {}

func (x *DeviceIncidentDropV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIncidentDropV1.ProtoReflect.Descriptor instead.
func (*DeviceIncidentDropV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceIncidentDropV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceIncidentDropV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceIncidentDropV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceIncidentDropV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceIncidentDropV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceIncidentDropV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceIncidentDropV1) GetProperties() *DeviceIncidentDropV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceIncidentDropV1Properties struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	Axis              *DeviceIncidentDropV1Properties_Axis `protobuf:"varint,1,opt,name=axis,proto3,enum=com.acme.platform.device.v1.DeviceIncidentDropV1Properties_Axis,oneof" json:"axis,omitempty"`
	DurationMs        *int64                               `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	PeakAccelerationG *float64                             `protobuf:"fixed64,3,opt,name=peak_acceleration_g,json=peakAccelerationG,proto3,oneof" json:"peak_acceleration_g,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceIncidentDropV1Properties) Reset() {
	*x = DeviceIncidentDropV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIncidentDropV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIncidentDropV1Properties) ProtoMessage() {}

func (x *DeviceIncidentDropV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIncidentDropV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceIncidentDropV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceIncidentDropV1Properties) GetAxis() DeviceIncidentDropV1Properties_Axis {
	if x != nil && x.Axis != nil {
		return *x.Axis
	}
	return DeviceIncidentDropV1Properties_AXIS_UNSPECIFIED
}

func (x *DeviceIncidentDropV1Properties) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *DeviceIncidentDropV1Properties) GetPeakAccelerationG() float64 {
	if x != nil && x.PeakAccelerationG != nil {
		return *x.PeakAccelerationG
	}
	return 0
}

// Device temperature exceeded a configured threshold.
type DeviceIncidentTemperatureV1 struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	EventName     string                                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                                  `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp                 `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                         `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                         `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceIncidentTemperatureV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIncidentTemperatureV1) Reset() {
	*x = DeviceIncidentTemperatureV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIncidentTemperatureV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIncidentTemperatureV1) ProtoMessage() {}

func (x *DeviceIncidentTemperatureV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIncidentTemperatureV1.ProtoReflect.Descriptor instead.
func (*DeviceIncidentTemperatureV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceIncidentTemperatureV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceIncidentTemperatureV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceIncidentTemperatureV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceIncidentTemperatureV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceIncidentTemperatureV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceIncidentTemperatureV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceIncidentTemperatureV1) GetProperties() *DeviceIncidentTemperatureV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceIncidentTemperatureV1Properties struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	BreachType    *DeviceIncidentTemperatureV1Properties_BreachType `protobuf:"varint,1,opt,name=breach_type,json=breachType,proto3,enum=com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties_BreachType,oneof" json:"breach_type,omitempty"`
	DegreesC      *float64                                          `protobuf:"fixed64,2,opt,name=degrees_c,json=degreesC,proto3,oneof" json:"degrees_c,omitempty"`
	ThresholdC    *float64                                          `protobuf:"fixed64,3,opt,name=threshold_c,json=thresholdC,proto3,oneof" json:"threshold_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIncidentTemperatureV1Properties) Reset() {
	*x = DeviceIncidentTemperatureV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIncidentTemperatureV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIncidentTemperatureV1Properties) ProtoMessage() {}

func (x *DeviceIncidentTemperatureV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIncidentTemperatureV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceIncidentTemperatureV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceIncidentTemperatureV1Properties) GetBreachType() DeviceIncidentTemperatureV1Properties_BreachType {
	if x != nil && x.BreachType != nil {
		return *x.BreachType
	}
	return DeviceIncidentTemperatureV1Properties_BREACH_TYPE_UNSPECIFIED
}

func (x *DeviceIncidentTemperatureV1Properties) GetDegreesC() float64 {
	if x != nil && x.DegreesC != nil {
		return *x.DegreesC
	}
	return 0
}

func (x *DeviceIncidentTemperatureV1Properties) GetThresholdC() float64 {
	if x != nil && x.ThresholdC != nil {
		return *x.ThresholdC
	}
	return 0
}

// Sensor calibration data snapshot from the device.
type DeviceInfoCalibrationV1 struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	EventName     string                             `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                              `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                             `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp             `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                     `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                     `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceInfoCalibrationV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoCalibrationV1) Reset() {
	*x = DeviceInfoCalibrationV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoCalibrationV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoCalibrationV1) ProtoMessage() {}

func (x *DeviceInfoCalibrationV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoCalibrationV1.ProtoReflect.Descriptor instead.
func (*DeviceInfoCalibrationV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceInfoCalibrationV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceInfoCalibrationV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceInfoCalibrationV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceInfoCalibrationV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceInfoCalibrationV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceInfoCalibrationV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceInfoCalibrationV1) GetProperties() *DeviceInfoCalibrationV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceInfoCalibrationV1Properties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concentration *float64               `protobuf:"fixed64,1,opt,name=concentration,proto3,oneof" json:"concentration,omitempty"`
	Integral      *int64                 `protobuf:"varint,2,opt,name=integral,proto3,oneof" json:"integral,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoCalibrationV1Properties) Reset() {
	*x = DeviceInfoCalibrationV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoCalibrationV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoCalibrationV1Properties) ProtoMessage() {}

func (x *DeviceInfoCalibrationV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoCalibrationV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceInfoCalibrationV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfoCalibrationV1Properties) GetConcentration() float64 {
	if x != nil && x.Concentration != nil {
		return *x.Concentration
	}
	return 0
}

func (x *DeviceInfoCalibrationV1Properties) GetIntegral() int64 {
	if x != nil && x.Integral != nil {
		return *x.Integral
	}
	return 0
}

func (x *DeviceInfoCalibrationV1Properties) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Hardware configuration read from device EEPROM at startup.
type DeviceInfoHardwareV1 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	EventName     string                          `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                           `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                          `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp          `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                  `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                  `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceInfoHardwareV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoHardwareV1) Reset() {
	*x = DeviceInfoHardwareV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoHardwareV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoHardwareV1) ProtoMessage() {}

func (x *DeviceInfoHardwareV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoHardwareV1.ProtoReflect.Descriptor instead.
func (*DeviceInfoHardwareV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceInfoHardwareV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceInfoHardwareV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceInfoHardwareV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceInfoHardwareV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceInfoHardwareV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceInfoHardwareV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceInfoHardwareV1) GetProperties() *DeviceInfoHardwareV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceInfoHardwareV1Properties struct {
	state                  protoimpl.MessageState                              `protogen:"open.v1"`
	EepromFormatVersion    *DeviceInfoHardwareV1Properties_EepromFormatVersion `protobuf:"bytes,1,opt,name=eeprom_format_version,json=eepromFormatVersion,proto3" json:"eeprom_format_version,omitempty"`
	FuelCellLotNumber      *string                                             `protobuf:"bytes,2,opt,name=fuel_cell_lot_number,json=fuelCellLotNumber,proto3,oneof" json:"fuel_cell_lot_number,omitempty"`
	FuelCellVendor         *string                                             `protobuf:"bytes,3,opt,name=fuel_cell_vendor,json=fuelCellVendor,proto3,oneof" json:"fuel_cell_vendor,omitempty"`
	ManufacturingTimestamp *timestamppb.Timestamp                              `protobuf:"bytes,4,opt,name=manufacturing_timestamp,json=manufacturingTimestamp,proto3,oneof" json:"manufacturing_timestamp,omitempty"`
	ModulePcbVersion       *DeviceInfoHardwareV1Properties_ModulePcbVersion    `protobuf:"bytes,5,opt,name=module_pcb_version,json=modulePcbVersion,proto3" json:"module_pcb_version,omitempty"`
	SensorType             *DeviceInfoHardwareV1Properties_SensorType          `protobuf:"varint,6,opt,name=sensor_type,json=sensorType,proto3,enum=com.acme.platform.device.v1.DeviceInfoHardwareV1Properties_SensorType,oneof" json:"sensor_type,omitempty"`
	UniqueId               *string                                             `protobuf:"bytes,7,opt,name=unique_id,json=uniqueId,proto3,oneof" json:"unique_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceInfoHardwareV1Properties) Reset() {
	*x = DeviceInfoHardwareV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoHardwareV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoHardwareV1Properties) ProtoMessage() {}

func (x *DeviceInfoHardwareV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoHardwareV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceInfoHardwareV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceInfoHardwareV1Properties) GetEepromFormatVersion() *DeviceInfoHardwareV1Properties_EepromFormatVersion {
	if x != nil {
		return x.EepromFormatVersion
	}
	return nil
}

func (x *DeviceInfoHardwareV1Properties) GetFuelCellLotNumber() string {
	if x != nil && x.FuelCellLotNumber != nil {
		return *x.FuelCellLotNumber
	}
	return ""
}

func (x *DeviceInfoHardwareV1Properties) GetFuelCellVendor() string {
	if x != nil && x.FuelCellVendor != nil {
		return *x.FuelCellVendor
	}
	return ""
}

func (x *DeviceInfoHardwareV1Properties) GetManufacturingTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ManufacturingTimestamp
	}
	return nil
}

func (x *DeviceInfoHardwareV1Properties) GetModulePcbVersion() *DeviceInfoHardwareV1Properties_ModulePcbVersion {
	if x != nil {
		return x.ModulePcbVersion
	}
	return nil
}

func (x *DeviceInfoHardwareV1Properties) GetSensorType() DeviceInfoHardwareV1Properties_SensorType {
	if x != nil && x.SensorType != nil {
		return *x.SensorType
	}
	return DeviceInfoHardwareV1Properties_SENSOR_TYPE_UNSPECIFIED
}

func (x *DeviceInfoHardwareV1Properties) GetUniqueId() string {
	if x != nil && x.UniqueId != nil {
		return *x.UniqueId
	}
	return ""
}

// Software version information reported by the device at startup.
type DeviceInfoSoftwareV1 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	EventName     string                          `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                           `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                          `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp          `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                  `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *DeviceContext                  `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *DeviceInfoSoftwareV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoSoftwareV1) Reset() {
	*x = DeviceInfoSoftwareV1{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoSoftwareV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoSoftwareV1) ProtoMessage() {}

func (x *DeviceInfoSoftwareV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoSoftwareV1.ProtoReflect.Descriptor instead.
func (*DeviceInfoSoftwareV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceInfoSoftwareV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DeviceInfoSoftwareV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *DeviceInfoSoftwareV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceInfoSoftwareV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *DeviceInfoSoftwareV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeviceInfoSoftwareV1) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeviceInfoSoftwareV1) GetProperties() *DeviceInfoSoftwareV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceInfoSoftwareV1Properties struct {
	state                         protoimpl.MessageState                   `protogen:"open.v1"`
	PcbaHwManufacturedTimestampMs *int64                                   `protobuf:"varint,11,opt,name=pcba_hw_manufactured_timestamp_ms,json=pcbaHwManufacturedTimestampMs,proto3,oneof" json:"pcba_hw_manufactured_timestamp_ms,omitempty"`
	PcbaHwVersion                 *string                                  `protobuf:"bytes,12,opt,name=pcba_hw_version,json=pcbaHwVersion,proto3,oneof" json:"pcba_hw_version,omitempty"`
	ProductType                   *string                                  `protobuf:"bytes,13,opt,name=product_type,json=productType,proto3,oneof" json:"product_type,omitempty"`
	SerialNumber                  *string                                  `protobuf:"bytes,14,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	UniqueId                      *int64                                   `protobuf:"varint,15,opt,name=unique_id,json=uniqueId,proto3,oneof" json:"unique_id,omitempty"`
	Versions                      *DeviceInfoSoftwareV1Properties_Versions `protobuf:"bytes,18,opt,name=versions,proto3" json:"versions,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *DeviceInfoSoftwareV1Properties) Reset() {
	*x = DeviceInfoSoftwareV1Properties{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoSoftwareV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoSoftwareV1Properties) ProtoMessage() {}

func (x *DeviceInfoSoftwareV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoSoftwareV1Properties.ProtoReflect.Descriptor instead.
func (*DeviceInfoSoftwareV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *DeviceInfoSoftwareV1Properties) GetPcbaHwManufacturedTimestampMs() int64 {
	if x != nil && x.PcbaHwManufacturedTimestampMs != nil {
		return *x.PcbaHwManufacturedTimestampMs
	}
	return 0
}

func (x *DeviceInfoSoftwareV1Properties) GetPcbaHwVersion() string {
	if x != nil && x.PcbaHwVersion != nil {
		return *x.PcbaHwVersion
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties) GetProductType() string {
	if x != nil && x.ProductType != nil {
		return *x.ProductType
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties) GetUniqueId() int64 {
	if x != nil && x.UniqueId != nil {
		return *x.UniqueId
	}
	return 0
}

func (x *DeviceInfoSoftwareV1Properties) GetVersions() *DeviceInfoSoftwareV1Properties_Versions {
	if x != nil {
		return x.Versions
	}
	return nil
}

type DeviceDiagnosticsStackUsageV1Properties_Threads struct {
	state          protoimpl.MessageState                                 `protogen:"open.v1"`
	Name           *string                                                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Priority       *int64                                                 `protobuf:"varint,2,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	StackSizeBytes *int64                                                 `protobuf:"varint,3,opt,name=stack_size_bytes,json=stackSizeBytes,proto3,oneof" json:"stack_size_bytes,omitempty"`
	StackUsedBytes *int64                                                 `protobuf:"varint,4,opt,name=stack_used_bytes,json=stackUsedBytes,proto3,oneof" json:"stack_used_bytes,omitempty"`
	State          *DeviceDiagnosticsStackUsageV1Properties_Threads_State `protobuf:"varint,5,opt,name=state,proto3,enum=com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties_Threads_State,oneof" json:"state,omitempty"`
	UsagePercent   *int64                                                 `protobuf:"varint,6,opt,name=usage_percent,json=usagePercent,proto3,oneof" json:"usage_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) Reset() {
	*x = DeviceDiagnosticsStackUsageV1Properties_Threads{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDiagnosticsStackUsageV1Properties_Threads) ProtoMessage() {}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDiagnosticsStackUsageV1Properties_Threads.ProtoReflect.Descriptor instead.
func (*DeviceDiagnosticsStackUsageV1Properties_Threads) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetPriority() int64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetStackSizeBytes() int64 {
	if x != nil && x.StackSizeBytes != nil {
		return *x.StackSizeBytes
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetStackUsedBytes() int64 {
	if x != nil && x.StackUsedBytes != nil {
		return *x.StackUsedBytes
	}
	return 0
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetState() DeviceDiagnosticsStackUsageV1Properties_Threads_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return DeviceDiagnosticsStackUsageV1Properties_Threads_STATE_UNSPECIFIED
}

func (x *DeviceDiagnosticsStackUsageV1Properties_Threads) GetUsagePercent() int64 {
	if x != nil && x.UsagePercent != nil {
		return *x.UsagePercent
	}
	return 0
}

type DeviceInfoHardwareV1Properties_EepromFormatVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *int64                 `protobuf:"varint,1,opt,name=major,proto3,oneof" json:"major,omitempty"`
	Minor         *int64                 `protobuf:"varint,2,opt,name=minor,proto3,oneof" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoHardwareV1Properties_EepromFormatVersion) Reset() {
	*x = DeviceInfoHardwareV1Properties_EepromFormatVersion{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoHardwareV1Properties_EepromFormatVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoHardwareV1Properties_EepromFormatVersion) ProtoMessage() {}

func (x *DeviceInfoHardwareV1Properties_EepromFormatVersion) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoHardwareV1Properties_EepromFormatVersion.ProtoReflect.Descriptor instead.
func (*DeviceInfoHardwareV1Properties_EepromFormatVersion) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DeviceInfoHardwareV1Properties_EepromFormatVersion) GetMajor() int64 {
	if x != nil && x.Major != nil {
		return *x.Major
	}
	return 0
}

func (x *DeviceInfoHardwareV1Properties_EepromFormatVersion) GetMinor() int64 {
	if x != nil && x.Minor != nil {
		return *x.Minor
	}
	return 0
}

type DeviceInfoHardwareV1Properties_ModulePcbVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         *int64                 `protobuf:"varint,1,opt,name=major,proto3,oneof" json:"major,omitempty"`
	Minor         *int64                 `protobuf:"varint,2,opt,name=minor,proto3,oneof" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoHardwareV1Properties_ModulePcbVersion) Reset() {
	*x = DeviceInfoHardwareV1Properties_ModulePcbVersion{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoHardwareV1Properties_ModulePcbVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoHardwareV1Properties_ModulePcbVersion) ProtoMessage() {}

func (x *DeviceInfoHardwareV1Properties_ModulePcbVersion) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoHardwareV1Properties_ModulePcbVersion.ProtoReflect.Descriptor instead.
func (*DeviceInfoHardwareV1Properties_ModulePcbVersion) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{10, 1}
}

func (x *DeviceInfoHardwareV1Properties_ModulePcbVersion) GetMajor() int64 {
	if x != nil && x.Major != nil {
		return *x.Major
	}
	return 0
}

func (x *DeviceInfoHardwareV1Properties_ModulePcbVersion) GetMinor() int64 {
	if x != nil && x.Minor != nil {
		return *x.Minor
	}
	return 0
}

type DeviceInfoSoftwareV1Properties_Versions struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AppGitSha                *string                `protobuf:"bytes,1,opt,name=app_git_sha,json=appGitSha,proto3,oneof" json:"app_git_sha,omitempty"`
	AppSemanticVersion       *string                `protobuf:"bytes,2,opt,name=app_semantic_version,json=appSemanticVersion,proto3,oneof" json:"app_semantic_version,omitempty"`
	BootloaderBuildTimestamp *int64                 `protobuf:"varint,3,opt,name=bootloader_build_timestamp,json=bootloaderBuildTimestamp,proto3,oneof" json:"bootloader_build_timestamp,omitempty"`
	BootloaderGitSha         *string                `protobuf:"bytes,4,opt,name=bootloader_git_sha,json=bootloaderGitSha,proto3,oneof" json:"bootloader_git_sha,omitempty"`
	BuildType                *string                `protobuf:"bytes,5,opt,name=build_type,json=buildType,proto3,oneof" json:"build_type,omitempty"`
	CompileTime              *string                `protobuf:"bytes,6,opt,name=compile_time,json=compileTime,proto3,oneof" json:"compile_time,omitempty"`
	CompiledBy               *string                `protobuf:"bytes,7,opt,name=compiled_by,json=compiledBy,proto3,oneof" json:"compiled_by,omitempty"`
	CompiledOnOs             *string                `protobuf:"bytes,8,opt,name=compiled_on_os,json=compiledOnOs,proto3,oneof" json:"compiled_on_os,omitempty"`
	CompilerVersion          *string                `protobuf:"bytes,9,opt,name=compiler_version,json=compilerVersion,proto3,oneof" json:"compiler_version,omitempty"`
	HwPlatform               *string                `protobuf:"bytes,10,opt,name=hw_platform,json=hwPlatform,proto3,oneof" json:"hw_platform,omitempty"`
	ZephyrKernelGitSha       *string                `protobuf:"bytes,11,opt,name=zephyr_kernel_git_sha,json=zephyrKernelGitSha,proto3,oneof" json:"zephyr_kernel_git_sha,omitempty"`
	ZephyrKernelVersion      *string                `protobuf:"bytes,12,opt,name=zephyr_kernel_version,json=zephyrKernelVersion,proto3,oneof" json:"zephyr_kernel_version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeviceInfoSoftwareV1Properties_Versions) Reset() {
	*x = DeviceInfoSoftwareV1Properties_Versions{}
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoSoftwareV1Properties_Versions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoSoftwareV1Properties_Versions) ProtoMessage() {}

func (x *DeviceInfoSoftwareV1Properties_Versions) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_device_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoSoftwareV1Properties_Versions.ProtoReflect.Descriptor instead.
func (*DeviceInfoSoftwareV1Properties_Versions) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_device_v1_events_proto_rawDescGZIP(), []int{12, 0}
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetAppGitSha() string {
	if x != nil && x.AppGitSha != nil {
		return *x.AppGitSha
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetAppSemanticVersion() string {
	if x != nil && x.AppSemanticVersion != nil {
		return *x.AppSemanticVersion
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetBootloaderBuildTimestamp() int64 {
	if x != nil && x.BootloaderBuildTimestamp != nil {
		return *x.BootloaderBuildTimestamp
	}
	return 0
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetBootloaderGitSha() string {
	if x != nil && x.BootloaderGitSha != nil {
		return *x.BootloaderGitSha
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetBuildType() string {
	if x != nil && x.BuildType != nil {
		return *x.BuildType
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetCompileTime() string {
	if x != nil && x.CompileTime != nil {
		return *x.CompileTime
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetCompiledBy() string {
	if x != nil && x.CompiledBy != nil {
		return *x.CompiledBy
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetCompiledOnOs() string {
	if x != nil && x.CompiledOnOs != nil {
		return *x.CompiledOnOs
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetCompilerVersion() string {
	if x != nil && x.CompilerVersion != nil {
		return *x.CompilerVersion
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetHwPlatform() string {
	if x != nil && x.HwPlatform != nil {
		return *x.HwPlatform
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetZephyrKernelGitSha() string {
	if x != nil && x.ZephyrKernelGitSha != nil {
		return *x.ZephyrKernelGitSha
	}
	return ""
}

func (x *DeviceInfoSoftwareV1Properties_Versions) GetZephyrKernelVersion() string {
	if x != nil && x.ZephyrKernelVersion != nil {
		return *x.ZephyrKernelVersion
	}
	return ""
}

var File_com_acme_platform_device_v1_events_proto protoreflect.FileDescriptor

const file_com_acme_platform_device_v1_events_proto_rawDesc = "" +
	"\n" +
	"(com/acme/platform/device/v1/events.proto\x12\x1bcom.acme.platform.device.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(com/acme/platform/common/v1/common.proto\"\xf0\x01\n" +
	"\rDeviceContext\x12 \n" +
	"\tdevice_id\x18\x01 \x01(\tH\x00R\bdeviceId\x88\x01\x01\x12.\n" +
	"\x10firmware_version\x18\x02 \x01(\tH\x01R\x0ffirmwareVersion\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x03 \x01(\tH\x02R\fserialNumber\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x04 \x01(\tH\x03R\btenantId\x88\x01\x01B\f\n" +
	"\n" +
	"_device_idB\x13\n" +
	"\x11_firmware_versionB\x10\n" +
	"\x0e_serial_numberB\f\n" +
	"\n" +
	"_tenant_id\"\x9e\x03\n" +
	"\x1dDeviceDiagnosticsStackUsageV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12d\n" +
	"\n" +
	"properties\x18\a \x01(\v2D.com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1PropertiesR\n" +
	"properties\"\x82\a\n" +
	"'DeviceDiagnosticsStackUsageV1Properties\x127\n" +
	"\x15highest_usage_percent\x18\x01 \x01(\x03H\x00R\x13highestUsagePercent\x88\x01\x01\x125\n" +
	"\x14highest_usage_thread\x18\x02 \x01(\tH\x01R\x12highestUsageThread\x88\x01\x01\x12&\n" +
	"\fthread_count\x18\x03 \x01(\x03H\x02R\vthreadCount\x88\x01\x01\x12f\n" +
	"\athreads\x18\x04 \x03(\v2L.com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.ThreadsR\athreads\x1a\x92\x04\n" +
	"\aThreads\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x02 \x01(\x03H\x01R\bpriority\x88\x01\x01\x12-\n" +
	"\x10stack_size_bytes\x18\x03 \x01(\x03H\x02R\x0estackSizeBytes\x88\x01\x01\x12-\n" +
	"\x10stack_used_bytes\x18\x04 \x01(\x03H\x03R\x0estackUsedBytes\x88\x01\x01\x12m\n" +
	"\x05state\x18\x05 \x01(\x0e2R.com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads.StateH\x04R\x05state\x88\x01\x01\x12(\n" +
	"\rusage_percent\x18\x06 \x01(\x03H\x05R\fusagePercent\x88\x01\x01\"z\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x0f\n" +
	"\vSTATE_READY\x10\x02\x12\x11\n" +
	"\rSTATE_PENDING\x10\x03\x12\x13\n" +
	"\x0fSTATE_SUSPENDED\x10\x04\x12\x0e\n" +
	"\n" +
	"STATE_DEAD\x10\x05B\a\n" +
	"\x05_nameB\v\n" +
	"\t_priorityB\x13\n" +
	"\x11_stack_size_bytesB\x13\n" +
	"\x11_stack_used_bytesB\b\n" +
	"\x06_stateB\x10\n" +
	"\x0e_usage_percentB\x18\n" +
	"\x16_highest_usage_percentB\x17\n" +
	"\x15_highest_usage_threadB\x0f\n" +
	"\r_thread_count\"\x8c\x03\n" +
	"\x14DeviceIncidentDropV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12[\n" +
	"\n" +
	"properties\x18\a \x01(\v2;.com.acme.platform.device.v1.DeviceIncidentDropV1PropertiesR\n" +
	"properties\"\xc9\x02\n" +
	"\x1eDeviceIncidentDropV1Properties\x12Y\n" +
	"\x04axis\x18\x01 \x01(\x0e2@.com.acme.platform.device.v1.DeviceIncidentDropV1Properties.AxisH\x00R\x04axis\x88\x01\x01\x12$\n" +
	"\vduration_ms\x18\x02 \x01(\x03H\x01R\n" +
	"durationMs\x88\x01\x01\x123\n" +
	"\x13peak_acceleration_g\x18\x03 \x01(\x01H\x02R\x11peakAccelerationG\x88\x01\x01\"@\n" +
	"\x04Axis\x12\x14\n" +
	"\x10AXIS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06AXIS_X\x10\x01\x12\n" +
	"\n" +
	"\x06AXIS_Y\x10\x02\x12\n" +
	"\n" +
	"\x06AXIS_Z\x10\x03B\a\n" +
	"\x05_axisB\x0e\n" +
	"\f_duration_msB\x16\n" +
	"\x14_peak_acceleration_g\"\x9a\x03\n" +
	"\x1bDeviceIncidentTemperatureV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12b\n" +
	"\n" +
	"properties\x18\a \x01(\v2B.com.acme.platform.device.v1.DeviceIncidentTemperatureV1PropertiesR\n" +
	"properties\"\xea\x02\n" +
	"%DeviceIncidentTemperatureV1Properties\x12s\n" +
	"\vbreach_type\x18\x01 \x01(\x0e2M.com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties.BreachTypeH\x00R\n" +
	"breachType\x88\x01\x01\x12 \n" +
	"\tdegrees_c\x18\x02 \x01(\x01H\x01R\bdegreesC\x88\x01\x01\x12$\n" +
	"\vthreshold_c\x18\x03 \x01(\x01H\x02R\n" +
	"thresholdC\x88\x01\x01\"V\n" +
	"\n" +
	"BreachType\x12\x1b\n" +
	"\x17BREACH_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BREACH_TYPE_OVER\x10\x01\x12\x15\n" +
	"\x11BREACH_TYPE_UNDER\x10\x02B\x0e\n" +
	"\f_breach_typeB\f\n" +
	"\n" +
	"_degrees_cB\x0e\n" +
	"\f_threshold_c\"\x92\x03\n" +
	"\x17DeviceInfoCalibrationV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12^\n" +
	"\n" +
	"properties\x18\a \x01(\v2>.com.acme.platform.device.v1.DeviceInfoCalibrationV1PropertiesR\n" +
	"properties\"\xdb\x01\n" +
	"!DeviceInfoCalibrationV1Properties\x12)\n" +
	"\rconcentration\x18\x01 \x01(\x01H\x00R\rconcentration\x88\x01\x01\x12\x1f\n" +
	"\bintegral\x18\x02 \x01(\x03H\x01R\bintegral\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\ttimestamp\x88\x01\x01B\x10\n" +
	"\x0e_concentrationB\v\n" +
	"\t_integralB\f\n" +
	"\n" +
	"_timestamp\"\x8c\x03\n" +
	"\x14DeviceInfoHardwareV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12[\n" +
	"\n" +
	"properties\x18\a \x01(\v2;.com.acme.platform.device.v1.DeviceInfoHardwareV1PropertiesR\n" +
	"properties\"\xa4\b\n" +
	"\x1eDeviceInfoHardwareV1Properties\x12\x83\x01\n" +
	"\x15eeprom_format_version\x18\x01 \x01(\v2O.com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.EepromFormatVersionR\x13eepromFormatVersion\x124\n" +
	"\x14fuel_cell_lot_number\x18\x02 \x01(\tH\x00R\x11fuelCellLotNumber\x88\x01\x01\x12-\n" +
	"\x10fuel_cell_vendor\x18\x03 \x01(\tH\x01R\x0efuelCellVendor\x88\x01\x01\x12X\n" +
	"\x17manufacturing_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x16manufacturingTimestamp\x88\x01\x01\x12z\n" +
	"\x12module_pcb_version\x18\x05 \x01(\v2L.com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.ModulePcbVersionR\x10modulePcbVersion\x12l\n" +
	"\vsensor_type\x18\x06 \x01(\x0e2F.com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.SensorTypeH\x03R\n" +
	"sensorType\x88\x01\x01\x12 \n" +
	"\tunique_id\x18\a \x01(\tH\x04R\buniqueId\x88\x01\x01\x1a_\n" +
	"\x13EepromFormatVersion\x12\x19\n" +
	"\x05major\x18\x01 \x01(\x03H\x00R\x05major\x88\x01\x01\x12\x19\n" +
	"\x05minor\x18\x02 \x01(\x03H\x01R\x05minor\x88\x01\x01B\b\n" +
	"\x06_majorB\b\n" +
	"\x06_minor\x1a\\\n" +
	"\x10ModulePcbVersion\x12\x19\n" +
	"\x05major\x18\x01 \x01(\x03H\x00R\x05major\x88\x01\x01\x12\x19\n" +
	"\x05minor\x18\x02 \x01(\x03H\x01R\x05minor\x88\x01\x01B\b\n" +
	"\x06_majorB\b\n" +
	"\x06_minor\"\x89\x01\n" +
	"\n" +
	"SensorType\x12\x1b\n" +
	"\x17SENSOR_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSENSOR_TYPE_CO\x10\x01\x12\x17\n" +
	"\x13SENSOR_TYPE_ALCOHOL\x10\x02\x12\x16\n" +
	"\x12SENSOR_TYPE_OXYGEN\x10\x03\x12\x19\n" +
	"\x15SENSOR_TYPE_FUEL_CELL\x10\x04B\x17\n" +
	"\x15_fuel_cell_lot_numberB\x13\n" +
	"\x11_fuel_cell_vendorB\x1a\n" +
	"\x18_manufacturing_timestampB\x0e\n" +
	"\f_sensor_typeB\f\n" +
	"\n" +
	"_unique_id\"\x8c\x03\n" +
	"\x14DeviceInfoSoftwareV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12D\n" +
	"\acontext\x18\x06 \x01(\v2*.com.acme.platform.device.v1.DeviceContextR\acontext\x12[\n" +
	"\n" +
	"properties\x18\a \x01(\v2;.com.acme.platform.device.v1.DeviceInfoSoftwareV1PropertiesR\n" +
	"properties\"\x9b\n" +
	"\n" +
	"\x1eDeviceInfoSoftwareV1Properties\x12M\n" +
	"!pcba_hw_manufactured_timestamp_ms\x18\v \x01(\x03H\x00R\x1dpcbaHwManufacturedTimestampMs\x88\x01\x01\x12+\n" +
	"\x0fpcba_hw_version\x18\f \x01(\tH\x01R\rpcbaHwVersion\x88\x01\x01\x12&\n" +
	"\fproduct_type\x18\r \x01(\tH\x02R\vproductType\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x0e \x01(\tH\x03R\fserialNumber\x88\x01\x01\x12 \n" +
	"\tunique_id\x18\x0f \x01(\x03H\x04R\buniqueId\x88\x01\x01\x12`\n" +
	"\bversions\x18\x12 \x01(\v2D.com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties.VersionsR\bversions\x1a\xbb\x06\n" +
	"\bVersions\x12#\n" +
	"\vapp_git_sha\x18\x01 \x01(\tH\x00R\tappGitSha\x88\x01\x01\x125\n" +
	"\x14app_semantic_version\x18\x02 \x01(\tH\x01R\x12appSemanticVersion\x88\x01\x01\x12A\n" +
	"\x1abootloader_build_timestamp\x18\x03 \x01(\x03H\x02R\x18bootloaderBuildTimestamp\x88\x01\x01\x121\n" +
	"\x12bootloader_git_sha\x18\x04 \x01(\tH\x03R\x10bootloaderGitSha\x88\x01\x01\x12\"\n" +
	"\n" +
	"build_type\x18\x05 \x01(\tH\x04R\tbuildType\x88\x01\x01\x12&\n" +
	"\fcompile_time\x18\x06 \x01(\tH\x05R\vcompileTime\x88\x01\x01\x12$\n" +
	"\vcompiled_by\x18\a \x01(\tH\x06R\n" +
	"compiledBy\x88\x01\x01\x12)\n" +
	"\x0ecompiled_on_os\x18\b \x01(\tH\aR\fcompiledOnOs\x88\x01\x01\x12.\n" +
	"\x10compiler_version\x18\t \x01(\tH\bR\x0fcompilerVersion\x88\x01\x01\x12$\n" +
	"\vhw_platform\x18\n" +
	" \x01(\tH\tR\n" +
	"hwPlatform\x88\x01\x01\x126\n" +
	"\x15zephyr_kernel_git_sha\x18\v \x01(\tH\n" +
	"R\x12zephyrKernelGitSha\x88\x01\x01\x127\n" +
	"\x15zephyr_kernel_version\x18\f \x01(\tH\vR\x13zephyrKernelVersion\x88\x01\x01B\x0e\n" +
	"\f_app_git_shaB\x17\n" +
	"\x15_app_semantic_versionB\x1d\n" +
	"\x1b_bootloader_build_timestampB\x15\n" +
	"\x13_bootloader_git_shaB\r\n" +
	"\v_build_typeB\x0f\n" +
	"\r_compile_timeB\x0e\n" +
	"\f_compiled_byB\x11\n" +
	"\x0f_compiled_on_osB\x13\n" +
	"\x11_compiler_versionB\x0e\n" +
	"\f_hw_platformB\x18\n" +
	"\x16_zephyr_kernel_git_shaB\x18\n" +
	"\x16_zephyr_kernel_versionB$\n" +
	"\"_pcba_hw_manufactured_timestamp_msB\x12\n" +
	"\x10_pcba_hw_versionB\x0f\n" +
	"\r_product_typeB\x10\n" +
	"\x0e_serial_numberB\f\n" +
	"\n" +
	"_unique_idBXZVgithub.com/sentiolabs/open-events/examples/demo/services/api/eventmap/pb/device;deviceb\x06proto3"

var (
	file_com_acme_platform_device_v1_events_proto_rawDescOnce sync.Once
	file_com_acme_platform_device_v1_events_proto_rawDescData []byte
)

func file_com_acme_platform_device_v1_events_proto_rawDescGZIP() []byte {
	file_com_acme_platform_device_v1_events_proto_rawDescOnce.Do(func() {
		file_com_acme_platform_device_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_acme_platform_device_v1_events_proto_rawDesc), len(file_com_acme_platform_device_v1_events_proto_rawDesc)))
	})
	return file_com_acme_platform_device_v1_events_proto_rawDescData
}

var file_com_acme_platform_device_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_com_acme_platform_device_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_com_acme_platform_device_v1_events_proto_goTypes = []any{
	(DeviceDiagnosticsStackUsageV1Properties_Threads_State)(0), // 0: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads.State
	(DeviceIncidentDropV1Properties_Axis)(0),                   // 1: com.acme.platform.device.v1.DeviceIncidentDropV1Properties.Axis
	(DeviceIncidentTemperatureV1Properties_BreachType)(0),      // 2: com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties.BreachType
	(DeviceInfoHardwareV1Properties_SensorType)(0),             // 3: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.SensorType
	(*DeviceContext)(nil),                                      // 4: com.acme.platform.device.v1.DeviceContext
	(*DeviceDiagnosticsStackUsageV1)(nil),                      // 5: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1
	(*DeviceDiagnosticsStackUsageV1Properties)(nil),            // 6: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties
	(*DeviceIncidentDropV1)(nil),                               // 7: com.acme.platform.device.v1.DeviceIncidentDropV1
	(*DeviceIncidentDropV1Properties)(nil),                     // 8: com.acme.platform.device.v1.DeviceIncidentDropV1Properties
	(*DeviceIncidentTemperatureV1)(nil),                        // 9: com.acme.platform.device.v1.DeviceIncidentTemperatureV1
	(*DeviceIncidentTemperatureV1Properties)(nil),              // 10: com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties
	(*DeviceInfoCalibrationV1)(nil),                            // 11: com.acme.platform.device.v1.DeviceInfoCalibrationV1
	(*DeviceInfoCalibrationV1Properties)(nil),                  // 12: com.acme.platform.device.v1.DeviceInfoCalibrationV1Properties
	(*DeviceInfoHardwareV1)(nil),                               // 13: com.acme.platform.device.v1.DeviceInfoHardwareV1
	(*DeviceInfoHardwareV1Properties)(nil),                     // 14: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties
	(*DeviceInfoSoftwareV1)(nil),                               // 15: com.acme.platform.device.v1.DeviceInfoSoftwareV1
	(*DeviceInfoSoftwareV1Properties)(nil),                     // 16: com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties
	(*DeviceDiagnosticsStackUsageV1Properties_Threads)(nil),    // 17: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads
	(*DeviceInfoHardwareV1Properties_EepromFormatVersion)(nil), // 18: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.EepromFormatVersion
	(*DeviceInfoHardwareV1Properties_ModulePcbVersion)(nil),    // 19: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.ModulePcbVersion
	(*DeviceInfoSoftwareV1Properties_Versions)(nil),            // 20: com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties.Versions
	(*timestamppb.Timestamp)(nil),                              // 21: google.protobuf.Timestamp
	(*common.Client)(nil),                                      // 22: com.acme.platform.common.v1.Client
}
var file_com_acme_platform_device_v1_events_proto_depIdxs = []int32{
	21, // 0: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 1: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 2: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	6,  // 3: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1.properties:type_name -> com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties
	17, // 4: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.threads:type_name -> com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads
	21, // 5: com.acme.platform.device.v1.DeviceIncidentDropV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 6: com.acme.platform.device.v1.DeviceIncidentDropV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 7: com.acme.platform.device.v1.DeviceIncidentDropV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	8,  // 8: com.acme.platform.device.v1.DeviceIncidentDropV1.properties:type_name -> com.acme.platform.device.v1.DeviceIncidentDropV1Properties
	1,  // 9: com.acme.platform.device.v1.DeviceIncidentDropV1Properties.axis:type_name -> com.acme.platform.device.v1.DeviceIncidentDropV1Properties.Axis
	21, // 10: com.acme.platform.device.v1.DeviceIncidentTemperatureV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 11: com.acme.platform.device.v1.DeviceIncidentTemperatureV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 12: com.acme.platform.device.v1.DeviceIncidentTemperatureV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	10, // 13: com.acme.platform.device.v1.DeviceIncidentTemperatureV1.properties:type_name -> com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties
	2,  // 14: com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties.breach_type:type_name -> com.acme.platform.device.v1.DeviceIncidentTemperatureV1Properties.BreachType
	21, // 15: com.acme.platform.device.v1.DeviceInfoCalibrationV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 16: com.acme.platform.device.v1.DeviceInfoCalibrationV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 17: com.acme.platform.device.v1.DeviceInfoCalibrationV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	12, // 18: com.acme.platform.device.v1.DeviceInfoCalibrationV1.properties:type_name -> com.acme.platform.device.v1.DeviceInfoCalibrationV1Properties
	21, // 19: com.acme.platform.device.v1.DeviceInfoCalibrationV1Properties.timestamp:type_name -> google.protobuf.Timestamp
	21, // 20: com.acme.platform.device.v1.DeviceInfoHardwareV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 21: com.acme.platform.device.v1.DeviceInfoHardwareV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 22: com.acme.platform.device.v1.DeviceInfoHardwareV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	14, // 23: com.acme.platform.device.v1.DeviceInfoHardwareV1.properties:type_name -> com.acme.platform.device.v1.DeviceInfoHardwareV1Properties
	18, // 24: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.eeprom_format_version:type_name -> com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.EepromFormatVersion
	21, // 25: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.manufacturing_timestamp:type_name -> google.protobuf.Timestamp
	19, // 26: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.module_pcb_version:type_name -> com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.ModulePcbVersion
	3,  // 27: com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.sensor_type:type_name -> com.acme.platform.device.v1.DeviceInfoHardwareV1Properties.SensorType
	21, // 28: com.acme.platform.device.v1.DeviceInfoSoftwareV1.event_ts:type_name -> google.protobuf.Timestamp
	22, // 29: com.acme.platform.device.v1.DeviceInfoSoftwareV1.client:type_name -> com.acme.platform.common.v1.Client
	4,  // 30: com.acme.platform.device.v1.DeviceInfoSoftwareV1.context:type_name -> com.acme.platform.device.v1.DeviceContext
	16, // 31: com.acme.platform.device.v1.DeviceInfoSoftwareV1.properties:type_name -> com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties
	20, // 32: com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties.versions:type_name -> com.acme.platform.device.v1.DeviceInfoSoftwareV1Properties.Versions
	0,  // 33: com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads.state:type_name -> com.acme.platform.device.v1.DeviceDiagnosticsStackUsageV1Properties.Threads.State
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_com_acme_platform_device_v1_events_proto_init() }
func file_com_acme_platform_device_v1_events_proto_init() {
	if File_com_acme_platform_device_v1_events_proto != nil {
		return
	}
	file_com_acme_platform_device_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[8].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[12].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[13].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[14].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[15].OneofWrappers = []any{}
	file_com_acme_platform_device_v1_events_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_acme_platform_device_v1_events_proto_rawDesc), len(file_com_acme_platform_device_v1_events_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_acme_platform_device_v1_events_proto_goTypes,
		DependencyIndexes: file_com_acme_platform_device_v1_events_proto_depIdxs,
		EnumInfos:         file_com_acme_platform_device_v1_events_proto_enumTypes,
		MessageInfos:      file_com_acme_platform_device_v1_events_proto_msgTypes,
	}.Build()
	File_com_acme_platform_device_v1_events_proto = out.File
	file_com_acme_platform_device_v1_events_proto_goTypes = nil
	file_com_acme_platform_device_v1_events_proto_depIdxs = nil
}
