package golang

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sentiolabs/open-events/internal/registry"
	"github.com/sentiolabs/open-events/internal/schemair"
)

const generatedHeader = "// Code generated by openevents. DO NOT EDIT."

// Emit writes per-domain Go bindings under cfg.Out for the given registry and lock.
// For each domain it produces:
//   - <cfg.Out>/<domain>/event_names.go  — one const per event
//   - <cfg.Out>/<domain>/context.go      — <DomainPascal>Context struct + Validate()
func Emit(reg registry.Registry, lock schemair.Lock, cfg Config) error {
	bundles := schemair.GroupByDomain(reg)
	for _, b := range bundles {
		dir := filepath.Join(cfg.Out, b.Domain.Name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %q: %w", dir, err)
		}

		if err := writeEventNames(dir, b); err != nil {
			return err
		}
		if err := writeContext(dir, b); err != nil {
			return err
		}
	}
	return nil
}

// writeEventNames emits <domain>/event_names.go.
func writeEventNames(dir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name

	// Sort events for determinism.
	events := append([]registry.Event(nil), b.Events...)
	sort.Slice(events, func(i, j int) bool {
		return wireKey(events[i]) < wireKey(events[j])
	})

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", domainName)

	if len(events) > 0 {
		sb.WriteString("const (\n")
		for _, ev := range events {
			ident := eventConstName(ev, domainName)
			wire := wireKey(ev)
			fmt.Fprintf(&sb, "\t%s = %q\n", ident, wire)
		}
		sb.WriteString(")\n")
	}

	return writeFile(filepath.Join(dir, "event_names.go"), sb.String())
}

// writeContext emits <domain>/context.go.
func writeContext(dir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name
	structName := pascalCase(domainName) + "Context"

	// Sort context fields for determinism.
	type namedField struct {
		name  string
		field registry.Field
	}
	fields := make([]namedField, 0, len(b.Domain.Context))
	for name, f := range b.Domain.Context {
		fields = append(fields, namedField{name: name, field: f})
	}
	sort.Slice(fields, func(i, j int) bool { return fields[i].name < fields[j].name })

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", domainName)

	// Struct definition.
	fmt.Fprintf(&sb, "type %s struct {\n", structName)
	for _, nf := range fields {
		goName := camelToExported(nf.name)
		goType := fieldGoType(nf.field)
		tag := buildJSONTag(nf.name, nf.field.Required)
		fmt.Fprintf(&sb, "\t%s %s `json:\"%s\"`\n", goName, goType, tag)
	}
	sb.WriteString("}\n\n")

	// FieldError type (local to this generated file so no import needed).
	sb.WriteString("// FieldError describes a validation error for a single context field.\n")
	sb.WriteString("type FieldError struct {\n")
	sb.WriteString("\tField   string\n")
	sb.WriteString("\tMessage string\n")
	sb.WriteString("}\n\n")

	// Validate method.
	fmt.Fprintf(&sb, "// Validate returns validation errors for required fields on %s.\n", structName)
	fmt.Fprintf(&sb, "func (c %s) Validate() []FieldError {\n", structName)
	sb.WriteString("\tvar errs []FieldError\n")
	for _, nf := range fields {
		if !nf.field.Required {
			continue
		}
		goName := camelToExported(nf.name)
		// Check emptiness for string-like types; for others just check zero-ish.
		switch nf.field.Type {
		case registry.FieldTypeString, registry.FieldTypeUUID, registry.FieldTypeDate, registry.FieldTypeEnum:
			fmt.Fprintf(&sb, "\tif c.%s == \"\" {\n", goName)
			fmt.Fprintf(&sb, "\t\terrs = append(errs, FieldError{Field: %q, Message: \"required\"})\n", nf.name)
			sb.WriteString("\t}\n")
		case registry.FieldTypeBoolean:
			// booleans have no "empty" — skip required check
		default:
			fmt.Fprintf(&sb, "\tif c.%s == 0 {\n", goName)
			fmt.Fprintf(&sb, "\t\terrs = append(errs, FieldError{Field: %q, Message: \"required\"})\n", nf.name)
			sb.WriteString("\t}\n")
		}
	}
	sb.WriteString("\treturn errs\n")
	sb.WriteString("}\n")

	return writeFile(filepath.Join(dir, "context.go"), sb.String())
}

// writeFile writes Go source content to path after running it through go/format
// so emitted files match what gofmt would produce. This keeps generated output
// stable under `gofmt -l` checks and avoids spurious diffs on re-run.
func writeFile(path, content string) error {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("format generated source for %q: %w", path, err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", path, err)
	}
	return nil
}

// wireKey returns "<name>@<version>".
func wireKey(ev registry.Event) string {
	return fmt.Sprintf("%s@%d", ev.Name, ev.Version)
}

// eventConstName derives the Go constant name for an event, dropping the domain
// prefix and appending V<version>. E.g. "user.auth.signup@1" in domain "user"
// becomes "AuthSignupV1".
func eventConstName(ev registry.Event, domain string) string {
	// Split the full event name on "." and drop the leading domain segment.
	parts := strings.Split(ev.Name, ".")
	if len(parts) > 0 && parts[0] == domain {
		parts = parts[1:]
	}
	var sb strings.Builder
	for _, p := range parts {
		sb.WriteString(camelSegment(p))
	}
	fmt.Fprintf(&sb, "V%d", ev.Version)
	return sb.String()
}

// camelSegment converts a snake_case or kebab-case segment to PascalCase.
func camelSegment(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	subs := strings.Split(s, "_")
	var b strings.Builder
	for _, sub := range subs {
		if sub == "" {
			continue
		}
		b.WriteString(strings.ToUpper(sub[:1]))
		b.WriteString(sub[1:])
	}
	return b.String()
}

// pascalCase converts a dot/snake/kebab identifier to PascalCase.
func pascalCase(s string) string {
	s = strings.ReplaceAll(s, ".", "_")
	return camelSegment(s)
}

// camelToExported converts a snake_case field name to an exported Go identifier.
// E.g. "tenant_id" → "TenantId".
func camelToExported(s string) string {
	return camelSegment(s)
}

// fieldGoType maps a registry FieldType to a Go type string.
func fieldGoType(f registry.Field) string {
	switch f.Type {
	case registry.FieldTypeString:
		return "string"
	case registry.FieldTypeInteger:
		return "int64"
	case registry.FieldTypeNumber:
		return "float64"
	case registry.FieldTypeBoolean:
		return "bool"
	case registry.FieldTypeTimestamp:
		return "string" // ISO-8601 string; proto/time.Time mapping handled by buf pipeline
	case registry.FieldTypeDate:
		return "string"
	case registry.FieldTypeUUID:
		return "string"
	case registry.FieldTypeEnum:
		return "string"
	case registry.FieldTypeArray:
		return "[]any"
	case registry.FieldTypeObject:
		return "map[string]any"
	default:
		return "any"
	}
}

// buildJSONTag builds the JSON struct tag value. Required fields omit omitempty;
// optional fields add it.
func buildJSONTag(name string, required bool) string {
	if required {
		return name
	}
	return name + ",omitempty"
}
