package golang_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sentiolabs/open-events/internal/codegen/codegentest"
	golang "github.com/sentiolabs/open-events/internal/codegen/golang"
	"github.com/sentiolabs/open-events/internal/registry"
	"github.com/sentiolabs/open-events/internal/schemair"
)

// buildTestRegistry returns the shared 2-domain test fixture from codegentest.
func buildTestRegistry(t *testing.T) (registry.Registry, schemair.Lock) {
	return codegentest.TwoDomainRegistry(t, codegentest.TwoDomainOptions{})
}

func TestEmit_CreatesExpectedFiles(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := golang.Config{Out: outDir, Package: "github.com/acme/platform/events"}
	if err := golang.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "user", "event_names.go"),
		filepath.Join(outDir, "user", "context.go"),
		filepath.Join(outDir, "device", "event_names.go"),
		filepath.Join(outDir, "device", "context.go"),
	}

	for _, path := range expectedFiles {
		if _, err := os.Stat(path); err != nil {
			t.Errorf("expected file %s to exist: %v", path, err)
		}
	}
}

func TestEmit_EventNamesContent(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := golang.Config{Out: outDir, Package: "github.com/acme/platform/events"}
	if err := golang.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	// user domain: user.auth.signup@1 → drop domain "user" → auth.signup → AuthSignupV1
	userNames, err := os.ReadFile(filepath.Join(outDir, "user", "event_names.go"))
	if err != nil {
		t.Fatalf("read user/event_names.go: %v", err)
	}
	userText := string(userNames)

	if !strings.Contains(userText, "// Code generated by openevents. DO NOT EDIT.") {
		t.Errorf("user/event_names.go missing generated header:\n%s", userText)
	}
	if !strings.Contains(userText, "package user") {
		t.Errorf("user/event_names.go missing package declaration:\n%s", userText)
	}
	if !strings.Contains(userText, `AuthSignupV1`) {
		t.Errorf("user/event_names.go missing AuthSignupV1 constant:\n%s", userText)
	}
	if !strings.Contains(userText, `"user.auth.signup@1"`) {
		t.Errorf("user/event_names.go missing wire value:\n%s", userText)
	}

	// device domain: device.info.hardware@1 → drop "device" → info.hardware → InfoHardwareV1
	deviceNames, err := os.ReadFile(filepath.Join(outDir, "device", "event_names.go"))
	if err != nil {
		t.Fatalf("read device/event_names.go: %v", err)
	}
	deviceText := string(deviceNames)

	if !strings.Contains(deviceText, "package device") {
		t.Errorf("device/event_names.go missing package declaration:\n%s", deviceText)
	}
	if !strings.Contains(deviceText, `InfoHardwareV1`) {
		t.Errorf("device/event_names.go missing InfoHardwareV1 constant:\n%s", deviceText)
	}
	if !strings.Contains(deviceText, `"device.info.hardware@1"`) {
		t.Errorf("device/event_names.go missing wire value:\n%s", deviceText)
	}
}

func TestEmit_ContextContent(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := golang.Config{Out: outDir, Package: "github.com/acme/platform/events"}
	if err := golang.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	// user domain: UserContext with tenant_id field
	userCtx, err := os.ReadFile(filepath.Join(outDir, "user", "context.go"))
	if err != nil {
		t.Fatalf("read user/context.go: %v", err)
	}
	userText := string(userCtx)

	if !strings.Contains(userText, "// Code generated by openevents. DO NOT EDIT.") {
		t.Errorf("user/context.go missing generated header:\n%s", userText)
	}
	if !strings.Contains(userText, "package user") {
		t.Errorf("user/context.go missing package declaration:\n%s", userText)
	}
	if !strings.Contains(userText, "type UserContext struct") {
		t.Errorf("user/context.go missing UserContext struct:\n%s", userText)
	}
	if !strings.Contains(userText, `json:"tenant_id"`) {
		t.Errorf("user/context.go missing tenant_id JSON tag:\n%s", userText)
	}
	if !strings.Contains(userText, "Validate()") {
		t.Errorf("user/context.go missing Validate() method:\n%s", userText)
	}

	// device domain: DeviceContext with device_id field
	deviceCtx, err := os.ReadFile(filepath.Join(outDir, "device", "context.go"))
	if err != nil {
		t.Fatalf("read device/context.go: %v", err)
	}
	deviceText := string(deviceCtx)

	if !strings.Contains(deviceText, "type DeviceContext struct") {
		t.Errorf("device/context.go missing DeviceContext struct:\n%s", deviceText)
	}
	if !strings.Contains(deviceText, `json:"device_id"`) {
		t.Errorf("device/context.go missing device_id JSON tag:\n%s", deviceText)
	}
}

func TestEmit_GeneratedFileHeader(t *testing.T) {
	reg, lock := buildTestRegistry(t)
	outDir := t.TempDir()

	cfg := golang.Config{Out: outDir, Package: "github.com/acme/platform/events"}
	if err := golang.Emit(reg, lock, cfg); err != nil {
		t.Fatalf("Emit() error = %v, want nil", err)
	}

	for _, rel := range []string{
		"user/event_names.go",
		"user/context.go",
		"device/event_names.go",
		"device/context.go",
	} {
		data, err := os.ReadFile(filepath.Join(outDir, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		if !strings.HasPrefix(string(data), "// Code generated by openevents. DO NOT EDIT.") {
			t.Errorf("%s must start with generated header, got:\n%s", rel, string(data[:min(len(data), 80)]))
		}
	}
}
