package golang

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sentiolabs/open-events/internal/registry"
	"github.com/sentiolabs/open-events/internal/schemair"
)

const generatedHeader = "// Code generated by openevents. DO NOT EDIT."

// Emit writes per-domain Go bindings under cfg.Out for the given registry and lock.
// For each domain it produces:
//   - <cfg.Out>/<domain>/event_names.go          — one const per event
//   - <cfg.Out>/<domain>/context.go              — <DomainPascal>Context struct
//   - <cfg.Out>/<domain>/<base>_request.go (×N)  — one per event: <Action>Request
//     struct + nested *Request types + Validate methods + enum value-set helpers
func Emit(reg registry.Registry, lock schemair.Lock, cfg Config) error {
	bundles := schemair.GroupByDomain(reg)
	for _, b := range bundles {
		dir := filepath.Join(cfg.Out, b.Domain.Name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %q: %w", dir, err)
		}

		if err := writeEventNames(dir, b); err != nil {
			return err
		}
		contextTypeName := pascalCase(b.Domain.Name) + "Context"
		if err := writeContext(dir, b); err != nil {
			return err
		}
		if err := writeEventRequests(dir, domainBundle{
			domain:          b.Domain.Name,
			contextTypeName: contextTypeName,
			eventmapImport:  cfg.Package,
			events:          b.Events,
		}); err != nil {
			return err
		}
	}
	return nil
}

// writeEventNames emits <domain>/event_names.go.
func writeEventNames(dir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name

	// Sort events for determinism.
	events := append([]registry.Event(nil), b.Events...)
	sort.Slice(events, func(i, j int) bool {
		return wireKey(events[i]) < wireKey(events[j])
	})

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", domainName)

	if len(events) > 0 {
		sb.WriteString("const (\n")
		for _, ev := range events {
			ident := eventConstName(ev, domainName)
			wire := wireKey(ev)
			fmt.Fprintf(&sb, "\t%s = %q\n", ident, wire)
		}
		sb.WriteString(")\n")
	}

	return writeFile(filepath.Join(dir, "event_names.go"), sb.String())
}

// writeContext emits <domain>/context.go.
func writeContext(dir string, b schemair.DomainBundle) error {
	domainName := b.Domain.Name
	structName := pascalCase(domainName) + "Context"

	// Sort context fields for determinism.
	type namedField struct {
		name  string
		field registry.Field
	}
	fields := make([]namedField, 0, len(b.Domain.Context))
	for name, f := range b.Domain.Context {
		fields = append(fields, namedField{name: name, field: f})
	}
	sort.Slice(fields, func(i, j int) bool { return fields[i].name < fields[j].name })

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	sb.WriteString("\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", domainName)

	// Struct definition. Validation lives in the hand-written validateContext
	// helper in each domain's helpers.go (not generated) so per-domain context
	// rules can encode runtime semantics the registry doesn't express.
	fmt.Fprintf(&sb, "type %s struct {\n", structName)
	for _, nf := range fields {
		goName := camelToExported(nf.name)
		goType := fieldGoType(nf.field)
		tag := buildJSONTag(nf.name, nf.field.Required)
		fmt.Fprintf(&sb, "\t%s %s `json:\"%s\"`\n", goName, goType, tag)
	}
	sb.WriteString("}\n")

	return writeFile(filepath.Join(dir, "context.go"), sb.String())
}

// writeFile writes Go source content to path after running it through go/format
// so emitted files match what gofmt would produce. This keeps generated output
// stable under `gofmt -l` checks and avoids spurious diffs on re-run.
func writeFile(path, content string) error {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("format generated source for %q: %w", path, err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", path, err)
	}
	return nil
}

// wireKey returns "<name>@<version>".
func wireKey(ev registry.Event) string {
	return fmt.Sprintf("%s@%d", ev.Name, ev.Version)
}

// eventConstName derives the Go constant name for an event, dropping the domain
// prefix and appending V<version>. E.g. "user.auth.signup@1" in domain "user"
// becomes "AuthSignupV1".
func eventConstName(ev registry.Event, domain string) string {
	// Split the full event name on "." and drop the leading domain segment.
	parts := strings.Split(ev.Name, ".")
	if len(parts) > 0 && parts[0] == domain {
		parts = parts[1:]
	}
	var sb strings.Builder
	for _, p := range parts {
		sb.WriteString(camelSegment(p))
	}
	fmt.Fprintf(&sb, "V%d", ev.Version)
	return sb.String()
}

// camelSegment converts a snake_case or kebab-case segment to PascalCase.
func camelSegment(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	subs := strings.Split(s, "_")
	var b strings.Builder
	for _, sub := range subs {
		if sub == "" {
			continue
		}
		b.WriteString(strings.ToUpper(sub[:1]))
		b.WriteString(sub[1:])
	}
	return b.String()
}

// pascalCase converts a dot/snake/kebab identifier to PascalCase.
func pascalCase(s string) string {
	s = strings.ReplaceAll(s, ".", "_")
	return camelSegment(s)
}

// camelToExported converts a snake_case field name to an exported Go
// identifier, applying Go initialism conventions for common acronyms
// (ID, URL, API, etc.). E.g. "tenant_id" → "TenantID", "user_url" → "UserURL".
func camelToExported(s string) string {
	parts := strings.Split(strings.ReplaceAll(s, "-", "_"), "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := goInitialisms[strings.ToUpper(p)]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// goInitialisms lists snake_case segments that should be rendered fully
// uppercase in Go identifiers, matching the Go community's initialism
// conventions (see https://github.com/golang/go/wiki/CodeReviewComments#initialisms).
// Keys are the uppercase form for case-insensitive lookup; values are the
// canonical Go rendering.
var goInitialisms = map[string]string{
	"ACL":   "ACL",
	"API":   "API",
	"ASCII": "ASCII",
	"CPU":   "CPU",
	"CSS":   "CSS",
	"DB":    "DB",
	"DNS":   "DNS",
	"EOF":   "EOF",
	"GUID":  "GUID",
	"HTML":  "HTML",
	"HTTP":  "HTTP",
	"HTTPS": "HTTPS",
	"ID":    "ID",
	"IP":    "IP",
	"JSON":  "JSON",
	"LHS":   "LHS",
	"OS":    "OS",
	"QPS":   "QPS",
	"RAM":   "RAM",
	"RHS":   "RHS",
	"RPC":   "RPC",
	"SLA":   "SLA",
	"SMTP":  "SMTP",
	"SKU":   "SKU",
	"SQL":   "SQL",
	"SSH":   "SSH",
	"TCP":   "TCP",
	"TLS":   "TLS",
	"TTL":   "TTL",
	"UDP":   "UDP",
	"UI":    "UI",
	"UID":   "UID",
	"UUID":  "UUID",
	"URI":   "URI",
	"URL":   "URL",
	"UTF8":  "UTF8",
	"VM":    "VM",
	"XML":   "XML",
	"XMPP":  "XMPP",
	"XSRF":  "XSRF",
	"XSS":   "XSS",
}

// fieldGoType maps a registry FieldType to a Go type string.
func fieldGoType(f registry.Field) string {
	switch f.Type {
	case registry.FieldTypeString:
		return "string"
	case registry.FieldTypeInteger:
		return "int64"
	case registry.FieldTypeNumber:
		return "float64"
	case registry.FieldTypeBoolean:
		return "bool"
	case registry.FieldTypeTimestamp:
		return "string" // ISO-8601 string; proto/time.Time mapping handled by buf pipeline
	case registry.FieldTypeDate:
		return "string"
	case registry.FieldTypeUUID:
		return "string"
	case registry.FieldTypeEnum:
		return "string"
	case registry.FieldTypeArray:
		return "[]any"
	case registry.FieldTypeObject:
		return "map[string]any"
	default:
		return "any"
	}
}

// buildJSONTag builds the JSON struct tag value. Required fields omit omitempty;
// optional fields add it.
func buildJSONTag(name string, required bool) string {
	if required {
		return name
	}
	return name + ",omitempty"
}
