#!/usr/bin/env bash
# Post-process buf-generated output:
#   1. Copy per-domain *.pb.go files into the API's eventmap/pb subdirectories.
#   2. Turn gen/python into an installable Python package.
set -euo pipefail

GEN_DIR="${1:?usage: postgen.sh <gen-dir> <api-eventmap-dir>}"
API_EVENTMAP_DIR="${2:?usage: postgen.sh <gen-dir> <api-eventmap-dir>}"

GO_GEN_DIR="$GEN_DIR/go"
PY_GEN_DIR="$GEN_DIR/python"

# ---------------------------------------------------------------------------
# 1. Copy buf-generated Go protobuf files into eventmap/pb/<domain>/.
#    buf (paths=source_relative) emits files at:
#      <GO_GEN_DIR>/com/acme/platform/<domain>/v1/*.pb.go
#    We copy them to:
#      <API_EVENTMAP_DIR>/pb/<domain>/*.pb.go
#    Proto types live in the "pb" subdirectory to avoid name collisions with
#    the JSON-binding types generated by openevents in eventmap/<domain>/.
# ---------------------------------------------------------------------------
PROTO_BASE="$GO_GEN_DIR/com/acme/platform"

if [[ ! -d "$PROTO_BASE" ]]; then
  echo "postgen: $PROTO_BASE not found; run buf generate first" >&2
  exit 1
fi

# Iterate over every domain that buf actually emitted under $PROTO_BASE/<domain>/v1.
# Hardcoding the domain list here would silently skip new domains added to the registry.
shopt -s nullglob
for domain_path in "$PROTO_BASE"/*/v1; do
  domain="$(basename "$(dirname "$domain_path")")"
  DST_DIR="$API_EVENTMAP_DIR/pb/$domain"
  mkdir -p "$DST_DIR"
  cp "$domain_path"/*.pb.go "$DST_DIR/"
  echo "postgen: copied $domain proto Go files to $DST_DIR"
done
shopt -u nullglob

# ---------------------------------------------------------------------------
# 2. Turn gen/python into an installable Python package.
# ---------------------------------------------------------------------------
if [[ ! -d "$PY_GEN_DIR" ]]; then
  echo "postgen: $PY_GEN_DIR not found; run buf generate first" >&2
  exit 1
fi

find "$PY_GEN_DIR" -type d -exec touch {}/__init__.py \;

if [[ -f "$PY_GEN_DIR/pyproject.toml" ]]; then
  echo "postgen: $PY_GEN_DIR/pyproject.toml already exists (preserved)"
else
  cat > "$PY_GEN_DIR/pyproject.toml" <<'PYTOML'
[project]
name = "openevents-demo-pb2"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = ["protobuf>=5.0"]

[tool.setuptools.packages.find]
where = ["."]
include = ["com*"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
PYTOML
  echo "postgen: $PY_GEN_DIR is now an installable package"
fi
