// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: com/acme/platform/user/v1/events.proto

package user

import (
	common "github.com/sentiolabs/open-events/examples/demo/services/api/eventmap/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserContext_Platform int32

const (
	UserContext_PLATFORM_UNSPECIFIED UserContext_Platform = 0
	UserContext_PLATFORM_IOS         UserContext_Platform = 1
	UserContext_PLATFORM_ANDROID     UserContext_Platform = 2
	UserContext_PLATFORM_WEB         UserContext_Platform = 3
)

// Enum value maps for UserContext_Platform.
var (
	UserContext_Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_IOS",
		2: "PLATFORM_ANDROID",
		3: "PLATFORM_WEB",
	}
	UserContext_Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_IOS":         1,
		"PLATFORM_ANDROID":     2,
		"PLATFORM_WEB":         3,
	}
)

func (x UserContext_Platform) Enum() *UserContext_Platform {
	p := new(UserContext_Platform)
	*p = x
	return p
}

func (x UserContext_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserContext_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_user_v1_events_proto_enumTypes[0].Descriptor()
}

func (UserContext_Platform) Type() protoreflect.EnumType {
	return &file_com_acme_platform_user_v1_events_proto_enumTypes[0]
}

func (x UserContext_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserContext_Platform.Descriptor instead.
func (UserContext_Platform) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

type UserAuthLoginV1Properties_Method int32

const (
	UserAuthLoginV1Properties_METHOD_UNSPECIFIED UserAuthLoginV1Properties_Method = 0
	UserAuthLoginV1Properties_METHOD_EMAIL       UserAuthLoginV1Properties_Method = 1
	UserAuthLoginV1Properties_METHOD_GOOGLE      UserAuthLoginV1Properties_Method = 2
	UserAuthLoginV1Properties_METHOD_APPLE       UserAuthLoginV1Properties_Method = 3
)

// Enum value maps for UserAuthLoginV1Properties_Method.
var (
	UserAuthLoginV1Properties_Method_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "METHOD_EMAIL",
		2: "METHOD_GOOGLE",
		3: "METHOD_APPLE",
	}
	UserAuthLoginV1Properties_Method_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"METHOD_EMAIL":       1,
		"METHOD_GOOGLE":      2,
		"METHOD_APPLE":       3,
	}
)

func (x UserAuthLoginV1Properties_Method) Enum() *UserAuthLoginV1Properties_Method {
	p := new(UserAuthLoginV1Properties_Method)
	*p = x
	return p
}

func (x UserAuthLoginV1Properties_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAuthLoginV1Properties_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_user_v1_events_proto_enumTypes[1].Descriptor()
}

func (UserAuthLoginV1Properties_Method) Type() protoreflect.EnumType {
	return &file_com_acme_platform_user_v1_events_proto_enumTypes[1]
}

func (x UserAuthLoginV1Properties_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAuthLoginV1Properties_Method.Descriptor instead.
func (UserAuthLoginV1Properties_Method) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{2, 0}
}

type UserAuthSignupV1Properties_Method int32

const (
	UserAuthSignupV1Properties_METHOD_UNSPECIFIED UserAuthSignupV1Properties_Method = 0
	UserAuthSignupV1Properties_METHOD_EMAIL       UserAuthSignupV1Properties_Method = 1
	UserAuthSignupV1Properties_METHOD_GOOGLE      UserAuthSignupV1Properties_Method = 2
	UserAuthSignupV1Properties_METHOD_APPLE       UserAuthSignupV1Properties_Method = 3
)

// Enum value maps for UserAuthSignupV1Properties_Method.
var (
	UserAuthSignupV1Properties_Method_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "METHOD_EMAIL",
		2: "METHOD_GOOGLE",
		3: "METHOD_APPLE",
	}
	UserAuthSignupV1Properties_Method_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"METHOD_EMAIL":       1,
		"METHOD_GOOGLE":      2,
		"METHOD_APPLE":       3,
	}
)

func (x UserAuthSignupV1Properties_Method) Enum() *UserAuthSignupV1Properties_Method {
	p := new(UserAuthSignupV1Properties_Method)
	*p = x
	return p
}

func (x UserAuthSignupV1Properties_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAuthSignupV1Properties_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_user_v1_events_proto_enumTypes[2].Descriptor()
}

func (UserAuthSignupV1Properties_Method) Type() protoreflect.EnumType {
	return &file_com_acme_platform_user_v1_events_proto_enumTypes[2]
}

func (x UserAuthSignupV1Properties_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAuthSignupV1Properties_Method.Descriptor instead.
func (UserAuthSignupV1Properties_Method) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{6, 0}
}

type UserCartCheckoutV1Properties_Currency int32

const (
	UserCartCheckoutV1Properties_CURRENCY_UNSPECIFIED UserCartCheckoutV1Properties_Currency = 0
	UserCartCheckoutV1Properties_CURRENCY_USD         UserCartCheckoutV1Properties_Currency = 1
	UserCartCheckoutV1Properties_CURRENCY_EUR         UserCartCheckoutV1Properties_Currency = 2
	UserCartCheckoutV1Properties_CURRENCY_GBP         UserCartCheckoutV1Properties_Currency = 3
)

// Enum value maps for UserCartCheckoutV1Properties_Currency.
var (
	UserCartCheckoutV1Properties_Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_USD",
		2: "CURRENCY_EUR",
		3: "CURRENCY_GBP",
	}
	UserCartCheckoutV1Properties_Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_USD":         1,
		"CURRENCY_EUR":         2,
		"CURRENCY_GBP":         3,
	}
)

func (x UserCartCheckoutV1Properties_Currency) Enum() *UserCartCheckoutV1Properties_Currency {
	p := new(UserCartCheckoutV1Properties_Currency)
	*p = x
	return p
}

func (x UserCartCheckoutV1Properties_Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCartCheckoutV1Properties_Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_user_v1_events_proto_enumTypes[3].Descriptor()
}

func (UserCartCheckoutV1Properties_Currency) Type() protoreflect.EnumType {
	return &file_com_acme_platform_user_v1_events_proto_enumTypes[3]
}

func (x UserCartCheckoutV1Properties_Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCartCheckoutV1Properties_Currency.Descriptor instead.
func (UserCartCheckoutV1Properties_Currency) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{8, 0}
}

type UserCartPurchaseV1Properties_PaymentMethod int32

const (
	UserCartPurchaseV1Properties_PAYMENT_METHOD_UNSPECIFIED UserCartPurchaseV1Properties_PaymentMethod = 0
	UserCartPurchaseV1Properties_PAYMENT_METHOD_CARD        UserCartPurchaseV1Properties_PaymentMethod = 1
	UserCartPurchaseV1Properties_PAYMENT_METHOD_APPLE_PAY   UserCartPurchaseV1Properties_PaymentMethod = 2
	UserCartPurchaseV1Properties_PAYMENT_METHOD_GOOGLE_PAY  UserCartPurchaseV1Properties_PaymentMethod = 3
)

// Enum value maps for UserCartPurchaseV1Properties_PaymentMethod.
var (
	UserCartPurchaseV1Properties_PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_APPLE_PAY",
		3: "PAYMENT_METHOD_GOOGLE_PAY",
	}
	UserCartPurchaseV1Properties_PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CARD":        1,
		"PAYMENT_METHOD_APPLE_PAY":   2,
		"PAYMENT_METHOD_GOOGLE_PAY":  3,
	}
)

func (x UserCartPurchaseV1Properties_PaymentMethod) Enum() *UserCartPurchaseV1Properties_PaymentMethod {
	p := new(UserCartPurchaseV1Properties_PaymentMethod)
	*p = x
	return p
}

func (x UserCartPurchaseV1Properties_PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCartPurchaseV1Properties_PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_platform_user_v1_events_proto_enumTypes[4].Descriptor()
}

func (UserCartPurchaseV1Properties_PaymentMethod) Type() protoreflect.EnumType {
	return &file_com_acme_platform_user_v1_events_proto_enumTypes[4]
}

func (x UserCartPurchaseV1Properties_PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCartPurchaseV1Properties_PaymentMethod.Descriptor instead.
func (UserCartPurchaseV1Properties_PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{12, 0}
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      *UserContext_Platform  `protobuf:"varint,1,opt,name=platform,proto3,enum=com.acme.platform.user.v1.UserContext_Platform,oneof" json:"platform,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	TenantId      *string                `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	UserId        *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserContext) GetPlatform() UserContext_Platform {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return UserContext_PLATFORM_UNSPECIFIED
}

func (x *UserContext) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *UserContext) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *UserContext) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

// User authenticated into their account.
type UserAuthLoginV1 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	EventName     string                     `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                      `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                     `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client             `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext               `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserAuthLoginV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthLoginV1) Reset() {
	*x = UserAuthLoginV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthLoginV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthLoginV1) ProtoMessage() {}

func (x *UserAuthLoginV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthLoginV1.ProtoReflect.Descriptor instead.
func (*UserAuthLoginV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserAuthLoginV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserAuthLoginV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserAuthLoginV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserAuthLoginV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserAuthLoginV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserAuthLoginV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserAuthLoginV1) GetProperties() *UserAuthLoginV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserAuthLoginV1Properties struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Method        *UserAuthLoginV1Properties_Method `protobuf:"varint,1,opt,name=method,proto3,enum=com.acme.platform.user.v1.UserAuthLoginV1Properties_Method,oneof" json:"method,omitempty"`
	Success       *bool                             `protobuf:"varint,2,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthLoginV1Properties) Reset() {
	*x = UserAuthLoginV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthLoginV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthLoginV1Properties) ProtoMessage() {}

func (x *UserAuthLoginV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthLoginV1Properties.ProtoReflect.Descriptor instead.
func (*UserAuthLoginV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthLoginV1Properties) GetMethod() UserAuthLoginV1Properties_Method {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return UserAuthLoginV1Properties_METHOD_UNSPECIFIED
}

func (x *UserAuthLoginV1Properties) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

// User session ended.
type UserAuthLogoutV1 struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventName     string                      `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                       `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                      `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client              `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext                `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserAuthLogoutV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthLogoutV1) Reset() {
	*x = UserAuthLogoutV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthLogoutV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthLogoutV1) ProtoMessage() {}

func (x *UserAuthLogoutV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthLogoutV1.ProtoReflect.Descriptor instead.
func (*UserAuthLogoutV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *UserAuthLogoutV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserAuthLogoutV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserAuthLogoutV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserAuthLogoutV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserAuthLogoutV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserAuthLogoutV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserAuthLogoutV1) GetProperties() *UserAuthLogoutV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserAuthLogoutV1Properties struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds *int64                 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserAuthLogoutV1Properties) Reset() {
	*x = UserAuthLogoutV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthLogoutV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthLogoutV1Properties) ProtoMessage() {}

func (x *UserAuthLogoutV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthLogoutV1Properties.ProtoReflect.Descriptor instead.
func (*UserAuthLogoutV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *UserAuthLogoutV1Properties) GetDurationSeconds() int64 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

// User completed account signup.
type UserAuthSignupV1 struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventName     string                      `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                       `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                      `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client              `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext                `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserAuthSignupV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthSignupV1) Reset() {
	*x = UserAuthSignupV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthSignupV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSignupV1) ProtoMessage() {}

func (x *UserAuthSignupV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSignupV1.ProtoReflect.Descriptor instead.
func (*UserAuthSignupV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *UserAuthSignupV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserAuthSignupV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserAuthSignupV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserAuthSignupV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserAuthSignupV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserAuthSignupV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserAuthSignupV1) GetProperties() *UserAuthSignupV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserAuthSignupV1Properties struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Method        *UserAuthSignupV1Properties_Method `protobuf:"varint,1,opt,name=method,proto3,enum=com.acme.platform.user.v1.UserAuthSignupV1Properties_Method,oneof" json:"method,omitempty"`
	Plan          *string                            `protobuf:"bytes,2,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthSignupV1Properties) Reset() {
	*x = UserAuthSignupV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthSignupV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSignupV1Properties) ProtoMessage() {}

func (x *UserAuthSignupV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSignupV1Properties.ProtoReflect.Descriptor instead.
func (*UserAuthSignupV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *UserAuthSignupV1Properties) GetMethod() UserAuthSignupV1Properties_Method {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return UserAuthSignupV1Properties_METHOD_UNSPECIFIED
}

func (x *UserAuthSignupV1Properties) GetPlan() string {
	if x != nil && x.Plan != nil {
		return *x.Plan
	}
	return ""
}

// User entered the checkout flow.
type UserCartCheckoutV1 struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	EventName     string                        `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                         `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                        `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext                  `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserCartCheckoutV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartCheckoutV1) Reset() {
	*x = UserCartCheckoutV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartCheckoutV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartCheckoutV1) ProtoMessage() {}

func (x *UserCartCheckoutV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartCheckoutV1.ProtoReflect.Descriptor instead.
func (*UserCartCheckoutV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *UserCartCheckoutV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserCartCheckoutV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserCartCheckoutV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserCartCheckoutV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserCartCheckoutV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserCartCheckoutV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserCartCheckoutV1) GetProperties() *UserCartCheckoutV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserCartCheckoutV1Properties struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	CartId        *string                                `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3,oneof" json:"cart_id,omitempty"`
	Currency      *UserCartCheckoutV1Properties_Currency `protobuf:"varint,2,opt,name=currency,proto3,enum=com.acme.platform.user.v1.UserCartCheckoutV1Properties_Currency,oneof" json:"currency,omitempty"`
	ItemCount     *int64                                 `protobuf:"varint,3,opt,name=item_count,json=itemCount,proto3,oneof" json:"item_count,omitempty"`
	SubtotalCents *int64                                 `protobuf:"varint,4,opt,name=subtotal_cents,json=subtotalCents,proto3,oneof" json:"subtotal_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartCheckoutV1Properties) Reset() {
	*x = UserCartCheckoutV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartCheckoutV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartCheckoutV1Properties) ProtoMessage() {}

func (x *UserCartCheckoutV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartCheckoutV1Properties.ProtoReflect.Descriptor instead.
func (*UserCartCheckoutV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *UserCartCheckoutV1Properties) GetCartId() string {
	if x != nil && x.CartId != nil {
		return *x.CartId
	}
	return ""
}

func (x *UserCartCheckoutV1Properties) GetCurrency() UserCartCheckoutV1Properties_Currency {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return UserCartCheckoutV1Properties_CURRENCY_UNSPECIFIED
}

func (x *UserCartCheckoutV1Properties) GetItemCount() int64 {
	if x != nil && x.ItemCount != nil {
		return *x.ItemCount
	}
	return 0
}

func (x *UserCartCheckoutV1Properties) GetSubtotalCents() int64 {
	if x != nil && x.SubtotalCents != nil {
		return *x.SubtotalCents
	}
	return 0
}

// User added an item to their cart.
type UserCartItemAddedV1 struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	EventName     string                         `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                          `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                         `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp         `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext                   `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserCartItemAddedV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartItemAddedV1) Reset() {
	*x = UserCartItemAddedV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartItemAddedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartItemAddedV1) ProtoMessage() {}

func (x *UserCartItemAddedV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartItemAddedV1.ProtoReflect.Descriptor instead.
func (*UserCartItemAddedV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *UserCartItemAddedV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserCartItemAddedV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserCartItemAddedV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserCartItemAddedV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserCartItemAddedV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserCartItemAddedV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserCartItemAddedV1) GetProperties() *UserCartItemAddedV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserCartItemAddedV1Properties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        *string                `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3,oneof" json:"cart_id,omitempty"`
	Quantity      *int64                 `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Sku           *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartItemAddedV1Properties) Reset() {
	*x = UserCartItemAddedV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartItemAddedV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartItemAddedV1Properties) ProtoMessage() {}

func (x *UserCartItemAddedV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartItemAddedV1Properties.ProtoReflect.Descriptor instead.
func (*UserCartItemAddedV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *UserCartItemAddedV1Properties) GetCartId() string {
	if x != nil && x.CartId != nil {
		return *x.CartId
	}
	return ""
}

func (x *UserCartItemAddedV1Properties) GetQuantity() int64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UserCartItemAddedV1Properties) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

// User completed a purchase and payment was accepted.
type UserCartPurchaseV1 struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	EventName     string                        `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventVersion  int64                         `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	EventId       string                        `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTs       *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Client        *common.Client                `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Context       *UserContext                  `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Properties    *UserCartPurchaseV1Properties `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartPurchaseV1) Reset() {
	*x = UserCartPurchaseV1{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartPurchaseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartPurchaseV1) ProtoMessage() {}

func (x *UserCartPurchaseV1) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartPurchaseV1.ProtoReflect.Descriptor instead.
func (*UserCartPurchaseV1) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *UserCartPurchaseV1) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *UserCartPurchaseV1) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *UserCartPurchaseV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserCartPurchaseV1) GetEventTs() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTs
	}
	return nil
}

func (x *UserCartPurchaseV1) GetClient() *common.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UserCartPurchaseV1) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UserCartPurchaseV1) GetProperties() *UserCartPurchaseV1Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UserCartPurchaseV1Properties struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	CartId        *string                                     `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3,oneof" json:"cart_id,omitempty"`
	CouponCode    *string                                     `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3,oneof" json:"coupon_code,omitempty"`
	OrderId       *string                                     `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	PaymentMethod *UserCartPurchaseV1Properties_PaymentMethod `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=com.acme.platform.user.v1.UserCartPurchaseV1Properties_PaymentMethod,oneof" json:"payment_method,omitempty"`
	TotalCents    *int64                                      `protobuf:"varint,5,opt,name=total_cents,json=totalCents,proto3,oneof" json:"total_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartPurchaseV1Properties) Reset() {
	*x = UserCartPurchaseV1Properties{}
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartPurchaseV1Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartPurchaseV1Properties) ProtoMessage() {}

func (x *UserCartPurchaseV1Properties) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_platform_user_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartPurchaseV1Properties.ProtoReflect.Descriptor instead.
func (*UserCartPurchaseV1Properties) Descriptor() ([]byte, []int) {
	return file_com_acme_platform_user_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *UserCartPurchaseV1Properties) GetCartId() string {
	if x != nil && x.CartId != nil {
		return *x.CartId
	}
	return ""
}

func (x *UserCartPurchaseV1Properties) GetCouponCode() string {
	if x != nil && x.CouponCode != nil {
		return *x.CouponCode
	}
	return ""
}

func (x *UserCartPurchaseV1Properties) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *UserCartPurchaseV1Properties) GetPaymentMethod() UserCartPurchaseV1Properties_PaymentMethod {
	if x != nil && x.PaymentMethod != nil {
		return *x.PaymentMethod
	}
	return UserCartPurchaseV1Properties_PAYMENT_METHOD_UNSPECIFIED
}

func (x *UserCartPurchaseV1Properties) GetTotalCents() int64 {
	if x != nil && x.TotalCents != nil {
		return *x.TotalCents
	}
	return 0
}

var File_com_acme_platform_user_v1_events_proto protoreflect.FileDescriptor

const file_com_acme_platform_user_v1_events_proto_rawDesc = "" +
	"\n" +
	"&com/acme/platform/user/v1/events.proto\x12\x19com.acme.platform.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(com/acme/platform/common/v1/common.proto\"\xd9\x02\n" +
	"\vUserContext\x12P\n" +
	"\bplatform\x18\x01 \x01(\x0e2/.com.acme.platform.user.v1.UserContext.PlatformH\x00R\bplatform\x88\x01\x01\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x01R\tsessionId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x03 \x01(\tH\x02R\btenantId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x03R\x06userId\x88\x01\x01\"^\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x02\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x03B\v\n" +
	"\t_platformB\r\n" +
	"\v_session_idB\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_user_id\"\xfc\x02\n" +
	"\x0fUserAuthLoginV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12T\n" +
	"\n" +
	"properties\x18\a \x01(\v24.com.acme.platform.user.v1.UserAuthLoginV1PropertiesR\n" +
	"properties\"\x84\x02\n" +
	"\x19UserAuthLoginV1Properties\x12X\n" +
	"\x06method\x18\x01 \x01(\x0e2;.com.acme.platform.user.v1.UserAuthLoginV1Properties.MethodH\x00R\x06method\x88\x01\x01\x12\x1d\n" +
	"\asuccess\x18\x02 \x01(\bH\x01R\asuccess\x88\x01\x01\"W\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMETHOD_EMAIL\x10\x01\x12\x11\n" +
	"\rMETHOD_GOOGLE\x10\x02\x12\x10\n" +
	"\fMETHOD_APPLE\x10\x03B\t\n" +
	"\a_methodB\n" +
	"\n" +
	"\b_success\"\xfe\x02\n" +
	"\x10UserAuthLogoutV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12U\n" +
	"\n" +
	"properties\x18\a \x01(\v25.com.acme.platform.user.v1.UserAuthLogoutV1PropertiesR\n" +
	"properties\"a\n" +
	"\x1aUserAuthLogoutV1Properties\x12.\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03H\x00R\x0fdurationSeconds\x88\x01\x01B\x13\n" +
	"\x11_duration_seconds\"\xfe\x02\n" +
	"\x10UserAuthSignupV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12U\n" +
	"\n" +
	"properties\x18\a \x01(\v25.com.acme.platform.user.v1.UserAuthSignupV1PropertiesR\n" +
	"properties\"\xfd\x01\n" +
	"\x1aUserAuthSignupV1Properties\x12Y\n" +
	"\x06method\x18\x01 \x01(\x0e2<.com.acme.platform.user.v1.UserAuthSignupV1Properties.MethodH\x00R\x06method\x88\x01\x01\x12\x17\n" +
	"\x04plan\x18\x02 \x01(\tH\x01R\x04plan\x88\x01\x01\"W\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMETHOD_EMAIL\x10\x01\x12\x11\n" +
	"\rMETHOD_GOOGLE\x10\x02\x12\x10\n" +
	"\fMETHOD_APPLE\x10\x03B\t\n" +
	"\a_methodB\a\n" +
	"\x05_plan\"\x82\x03\n" +
	"\x12UserCartCheckoutV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12W\n" +
	"\n" +
	"properties\x18\a \x01(\v27.com.acme.platform.user.v1.UserCartCheckoutV1PropertiesR\n" +
	"properties\"\x86\x03\n" +
	"\x1cUserCartCheckoutV1Properties\x12\x1c\n" +
	"\acart_id\x18\x01 \x01(\tH\x00R\x06cartId\x88\x01\x01\x12a\n" +
	"\bcurrency\x18\x02 \x01(\x0e2@.com.acme.platform.user.v1.UserCartCheckoutV1Properties.CurrencyH\x01R\bcurrency\x88\x01\x01\x12\"\n" +
	"\n" +
	"item_count\x18\x03 \x01(\x03H\x02R\titemCount\x88\x01\x01\x12*\n" +
	"\x0esubtotal_cents\x18\x04 \x01(\x03H\x03R\rsubtotalCents\x88\x01\x01\"Z\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_USD\x10\x01\x12\x10\n" +
	"\fCURRENCY_EUR\x10\x02\x12\x10\n" +
	"\fCURRENCY_GBP\x10\x03B\n" +
	"\n" +
	"\b_cart_idB\v\n" +
	"\t_currencyB\r\n" +
	"\v_item_countB\x11\n" +
	"\x0f_subtotal_cents\"\x84\x03\n" +
	"\x13UserCartItemAddedV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12X\n" +
	"\n" +
	"properties\x18\a \x01(\v28.com.acme.platform.user.v1.UserCartItemAddedV1PropertiesR\n" +
	"properties\"\x96\x01\n" +
	"\x1dUserCartItemAddedV1Properties\x12\x1c\n" +
	"\acart_id\x18\x01 \x01(\tH\x00R\x06cartId\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x03H\x01R\bquantity\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x02R\x03sku\x88\x01\x01B\n" +
	"\n" +
	"\b_cart_idB\v\n" +
	"\t_quantityB\x06\n" +
	"\x04_sku\"\x82\x03\n" +
	"\x12UserCartPurchaseV1\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x125\n" +
	"\bevent_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventTs\x12;\n" +
	"\x06client\x18\x05 \x01(\v2#.com.acme.platform.common.v1.ClientR\x06client\x12@\n" +
	"\acontext\x18\x06 \x01(\v2&.com.acme.platform.user.v1.UserContextR\acontext\x12W\n" +
	"\n" +
	"properties\x18\a \x01(\v27.com.acme.platform.user.v1.UserCartPurchaseV1PropertiesR\n" +
	"properties\"\xef\x03\n" +
	"\x1cUserCartPurchaseV1Properties\x12\x1c\n" +
	"\acart_id\x18\x01 \x01(\tH\x00R\x06cartId\x88\x01\x01\x12$\n" +
	"\vcoupon_code\x18\x02 \x01(\tH\x01R\n" +
	"couponCode\x88\x01\x01\x12\x1e\n" +
	"\border_id\x18\x03 \x01(\tH\x02R\aorderId\x88\x01\x01\x12q\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2E.com.acme.platform.user.v1.UserCartPurchaseV1Properties.PaymentMethodH\x03R\rpaymentMethod\x88\x01\x01\x12$\n" +
	"\vtotal_cents\x18\x05 \x01(\x03H\x04R\n" +
	"totalCents\x88\x01\x01\"\x85\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_METHOD_APPLE_PAY\x10\x02\x12\x1d\n" +
	"\x19PAYMENT_METHOD_GOOGLE_PAY\x10\x03B\n" +
	"\n" +
	"\b_cart_idB\x0e\n" +
	"\f_coupon_codeB\v\n" +
	"\t_order_idB\x11\n" +
	"\x0f_payment_methodB\x0e\n" +
	"\f_total_centsBTZRgithub.com/sentiolabs/open-events/examples/demo/services/api/eventmap/pb/user;userb\x06proto3"

var (
	file_com_acme_platform_user_v1_events_proto_rawDescOnce sync.Once
	file_com_acme_platform_user_v1_events_proto_rawDescData []byte
)

func file_com_acme_platform_user_v1_events_proto_rawDescGZIP() []byte {
	file_com_acme_platform_user_v1_events_proto_rawDescOnce.Do(func() {
		file_com_acme_platform_user_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_acme_platform_user_v1_events_proto_rawDesc), len(file_com_acme_platform_user_v1_events_proto_rawDesc)))
	})
	return file_com_acme_platform_user_v1_events_proto_rawDescData
}

var file_com_acme_platform_user_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_com_acme_platform_user_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_com_acme_platform_user_v1_events_proto_goTypes = []any{
	(UserContext_Platform)(0),                       // 0: com.acme.platform.user.v1.UserContext.Platform
	(UserAuthLoginV1Properties_Method)(0),           // 1: com.acme.platform.user.v1.UserAuthLoginV1Properties.Method
	(UserAuthSignupV1Properties_Method)(0),          // 2: com.acme.platform.user.v1.UserAuthSignupV1Properties.Method
	(UserCartCheckoutV1Properties_Currency)(0),      // 3: com.acme.platform.user.v1.UserCartCheckoutV1Properties.Currency
	(UserCartPurchaseV1Properties_PaymentMethod)(0), // 4: com.acme.platform.user.v1.UserCartPurchaseV1Properties.PaymentMethod
	(*UserContext)(nil),                             // 5: com.acme.platform.user.v1.UserContext
	(*UserAuthLoginV1)(nil),                         // 6: com.acme.platform.user.v1.UserAuthLoginV1
	(*UserAuthLoginV1Properties)(nil),               // 7: com.acme.platform.user.v1.UserAuthLoginV1Properties
	(*UserAuthLogoutV1)(nil),                        // 8: com.acme.platform.user.v1.UserAuthLogoutV1
	(*UserAuthLogoutV1Properties)(nil),              // 9: com.acme.platform.user.v1.UserAuthLogoutV1Properties
	(*UserAuthSignupV1)(nil),                        // 10: com.acme.platform.user.v1.UserAuthSignupV1
	(*UserAuthSignupV1Properties)(nil),              // 11: com.acme.platform.user.v1.UserAuthSignupV1Properties
	(*UserCartCheckoutV1)(nil),                      // 12: com.acme.platform.user.v1.UserCartCheckoutV1
	(*UserCartCheckoutV1Properties)(nil),            // 13: com.acme.platform.user.v1.UserCartCheckoutV1Properties
	(*UserCartItemAddedV1)(nil),                     // 14: com.acme.platform.user.v1.UserCartItemAddedV1
	(*UserCartItemAddedV1Properties)(nil),           // 15: com.acme.platform.user.v1.UserCartItemAddedV1Properties
	(*UserCartPurchaseV1)(nil),                      // 16: com.acme.platform.user.v1.UserCartPurchaseV1
	(*UserCartPurchaseV1Properties)(nil),            // 17: com.acme.platform.user.v1.UserCartPurchaseV1Properties
	(*timestamppb.Timestamp)(nil),                   // 18: google.protobuf.Timestamp
	(*common.Client)(nil),                           // 19: com.acme.platform.common.v1.Client
}
var file_com_acme_platform_user_v1_events_proto_depIdxs = []int32{
	0,  // 0: com.acme.platform.user.v1.UserContext.platform:type_name -> com.acme.platform.user.v1.UserContext.Platform
	18, // 1: com.acme.platform.user.v1.UserAuthLoginV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 2: com.acme.platform.user.v1.UserAuthLoginV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 3: com.acme.platform.user.v1.UserAuthLoginV1.context:type_name -> com.acme.platform.user.v1.UserContext
	7,  // 4: com.acme.platform.user.v1.UserAuthLoginV1.properties:type_name -> com.acme.platform.user.v1.UserAuthLoginV1Properties
	1,  // 5: com.acme.platform.user.v1.UserAuthLoginV1Properties.method:type_name -> com.acme.platform.user.v1.UserAuthLoginV1Properties.Method
	18, // 6: com.acme.platform.user.v1.UserAuthLogoutV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 7: com.acme.platform.user.v1.UserAuthLogoutV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 8: com.acme.platform.user.v1.UserAuthLogoutV1.context:type_name -> com.acme.platform.user.v1.UserContext
	9,  // 9: com.acme.platform.user.v1.UserAuthLogoutV1.properties:type_name -> com.acme.platform.user.v1.UserAuthLogoutV1Properties
	18, // 10: com.acme.platform.user.v1.UserAuthSignupV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 11: com.acme.platform.user.v1.UserAuthSignupV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 12: com.acme.platform.user.v1.UserAuthSignupV1.context:type_name -> com.acme.platform.user.v1.UserContext
	11, // 13: com.acme.platform.user.v1.UserAuthSignupV1.properties:type_name -> com.acme.platform.user.v1.UserAuthSignupV1Properties
	2,  // 14: com.acme.platform.user.v1.UserAuthSignupV1Properties.method:type_name -> com.acme.platform.user.v1.UserAuthSignupV1Properties.Method
	18, // 15: com.acme.platform.user.v1.UserCartCheckoutV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 16: com.acme.platform.user.v1.UserCartCheckoutV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 17: com.acme.platform.user.v1.UserCartCheckoutV1.context:type_name -> com.acme.platform.user.v1.UserContext
	13, // 18: com.acme.platform.user.v1.UserCartCheckoutV1.properties:type_name -> com.acme.platform.user.v1.UserCartCheckoutV1Properties
	3,  // 19: com.acme.platform.user.v1.UserCartCheckoutV1Properties.currency:type_name -> com.acme.platform.user.v1.UserCartCheckoutV1Properties.Currency
	18, // 20: com.acme.platform.user.v1.UserCartItemAddedV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 21: com.acme.platform.user.v1.UserCartItemAddedV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 22: com.acme.platform.user.v1.UserCartItemAddedV1.context:type_name -> com.acme.platform.user.v1.UserContext
	15, // 23: com.acme.platform.user.v1.UserCartItemAddedV1.properties:type_name -> com.acme.platform.user.v1.UserCartItemAddedV1Properties
	18, // 24: com.acme.platform.user.v1.UserCartPurchaseV1.event_ts:type_name -> google.protobuf.Timestamp
	19, // 25: com.acme.platform.user.v1.UserCartPurchaseV1.client:type_name -> com.acme.platform.common.v1.Client
	5,  // 26: com.acme.platform.user.v1.UserCartPurchaseV1.context:type_name -> com.acme.platform.user.v1.UserContext
	17, // 27: com.acme.platform.user.v1.UserCartPurchaseV1.properties:type_name -> com.acme.platform.user.v1.UserCartPurchaseV1Properties
	4,  // 28: com.acme.platform.user.v1.UserCartPurchaseV1Properties.payment_method:type_name -> com.acme.platform.user.v1.UserCartPurchaseV1Properties.PaymentMethod
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_com_acme_platform_user_v1_events_proto_init() }
func file_com_acme_platform_user_v1_events_proto_init() {
	if File_com_acme_platform_user_v1_events_proto != nil {
		return
	}
	file_com_acme_platform_user_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[8].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_com_acme_platform_user_v1_events_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_acme_platform_user_v1_events_proto_rawDesc), len(file_com_acme_platform_user_v1_events_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_acme_platform_user_v1_events_proto_goTypes,
		DependencyIndexes: file_com_acme_platform_user_v1_events_proto_depIdxs,
		EnumInfos:         file_com_acme_platform_user_v1_events_proto_enumTypes,
		MessageInfos:      file_com_acme_platform_user_v1_events_proto_msgTypes,
	}.Build()
	File_com_acme_platform_user_v1_events_proto = out.File
	file_com_acme_platform_user_v1_events_proto_goTypes = nil
	file_com_acme_platform_user_v1_events_proto_depIdxs = nil
}
