# Code generated by openevents. DO NOT EDIT.
from dataclasses import dataclass
from typing import Optional


@dataclass
class DeviceContext:
    device_id: str
    tenant_id: str
    firmware_version: Optional[str] = None
    serial_number: Optional[str] = None
