# Code generated by openevents. DO NOT EDIT.
from dataclasses import dataclass
from typing import Optional


@dataclass
class UserContext:
    platform: str
    tenant_id: str
    session_id: Optional[str] = None
    user_id: Optional[str] = None
