# Code generated by openevents. DO NOT EDIT.
DIAGNOSTICS_STACK_USAGE_V1 = "device.diagnostics.stack_usage@1"
INCIDENT_DROP_V1 = "device.incident.drop@1"
INCIDENT_TEMPERATURE_V1 = "device.incident.temperature@1"
INFO_CALIBRATION_V1 = "device.info.calibration@1"
INFO_HARDWARE_V1 = "device.info.hardware@1"
INFO_SOFTWARE_V1 = "device.info.software@1"
