# Code generated by openevents. DO NOT EDIT.
AUTH_LOGIN_V1 = "user.auth.login@1"
AUTH_LOGOUT_V1 = "user.auth.logout@1"
AUTH_SIGNUP_V1 = "user.auth.signup@1"
CART_CHECKOUT_V1 = "user.cart.checkout@1"
CART_ITEM_ADDED_V1 = "user.cart.item_added@1"
CART_PURCHASE_V1 = "user.cart.purchase@1"
