package constgen

import (
	"strings"
	"testing"

	"github.com/sentiolabs/open-events/internal/registry"
)

func TestEntries_SortedByWireAndShaped(t *testing.T) {
	reg := registry.Registry{Events: []registry.Event{
		{Name: "search.performed", Version: 1},
		{Name: "checkout.started", Version: 1},
		{Name: "checkout.completed", Version: 2},
	}}

	got := Entries(reg)
	want := []Entry{
		{GoIdent: "CheckoutCompletedV2", PyIdent: "CHECKOUT_COMPLETED_V2", Wire: "checkout.completed@2"},
		{GoIdent: "CheckoutStartedV1", PyIdent: "CHECKOUT_STARTED_V1", Wire: "checkout.started@1"},
		{GoIdent: "SearchPerformedV1", PyIdent: "SEARCH_PERFORMED_V1", Wire: "search.performed@1"},
	}

	if len(got) != len(want) {
		t.Fatalf("len(Entries) = %d, want %d", len(got), len(want))
	}
	for i := range got {
		if got[i] != want[i] {
			t.Fatalf("Entries[%d] = %+v, want %+v", i, got[i], want[i])
		}
	}
}

func TestEntries_HandlesHyphensAndUnderscores(t *testing.T) {
	reg := registry.Registry{Events: []registry.Event{
		{Name: "user.signed-up", Version: 3},
		{Name: "user.profile_changed", Version: 1},
	}}

	got := Entries(reg)
	wantIdents := map[string]string{
		"user.profile_changed@1": "UserProfileChangedV1",
		"user.signed-up@3":       "UserSignedUpV3",
	}
	for _, e := range got {
		if got, ok := wantIdents[e.Wire]; !ok || got != e.GoIdent {
			t.Fatalf("Wire=%q GoIdent=%q want %q", e.Wire, e.GoIdent, got)
		}
	}
}

func TestRenderGo(t *testing.T) {
	entries := []Entry{
		{GoIdent: "CheckoutStartedV1", PyIdent: "CHECKOUT_STARTED_V1", Wire: "checkout.started@1"},
		{GoIdent: "SearchPerformedV1", PyIdent: "SEARCH_PERFORMED_V1", Wire: "search.performed@1"},
	}

	got, err := RenderGo("eventmap", entries)
	if err != nil {
		t.Fatalf("RenderGo() error = %v", err)
	}
	gotStr := string(got)

	for _, want := range []string{
		"// Code generated by openevents generate constants. DO NOT EDIT.",
		"package eventmap",
		"const (",
		`CheckoutStartedV1 = "checkout.started@1"`,
		`SearchPerformedV1 = "search.performed@1"`,
		"func AllEventNames() []string {",
	} {
		if !strings.Contains(gotStr, want) {
			t.Fatalf("RenderGo() missing %q\n%s", want, gotStr)
		}
	}
}

func TestRenderGo_EmptyPackageRejected(t *testing.T) {
	if _, err := RenderGo("", nil); err == nil {
		t.Fatalf("RenderGo(\"\") error = nil, want non-nil")
	}
}

func TestRenderPython(t *testing.T) {
	entries := []Entry{
		{GoIdent: "CheckoutStartedV1", PyIdent: "CHECKOUT_STARTED_V1", Wire: "checkout.started@1"},
		{GoIdent: "SearchPerformedV1", PyIdent: "SEARCH_PERFORMED_V1", Wire: "search.performed@1"},
	}

	got, err := RenderPython(entries)
	if err != nil {
		t.Fatalf("RenderPython() error = %v", err)
	}
	gotStr := string(got)

	for _, want := range []string{
		`"""Generated by openevents generate constants. DO NOT EDIT."""`,
		`CHECKOUT_STARTED_V1 = "checkout.started@1"`,
		`SEARCH_PERFORMED_V1 = "search.performed@1"`,
		"ALL_EVENT_NAMES: tuple[str, ...] = (",
	} {
		if !strings.Contains(gotStr, want) {
			t.Fatalf("RenderPython() missing %q\n%s", want, gotStr)
		}
	}
}
