// Package constgen emits cross-language event-name constants from an OpenEvents
// registry. The registry is the single source of truth for the canonical
// "<name>@<version>" strings used as SQS routing attributes, log labels, and
// generally anywhere producer and consumer must agree on what an event is.
package constgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/sentiolabs/open-events/internal/registry"
)

// Entry is a single registry event surfaced as a generated constant.
type Entry struct {
	// GoIdent is the Go identifier (CamelCase + V<version>), e.g. "CheckoutStartedV1".
	GoIdent string
	// PyIdent is the Python identifier (SCREAMING_SNAKE + _V<version>), e.g. "CHECKOUT_STARTED_V1".
	PyIdent string
	// Wire is the "<name>@<version>" string that appears on the wire.
	Wire string
}

// Entries returns one Entry per registry event, sorted by wire name for
// determinism.
func Entries(reg registry.Registry) []Entry {
	entries := make([]Entry, 0, len(reg.Events))
	for _, ev := range reg.Events {
		entries = append(entries, Entry{
			GoIdent: goIdent(ev.Name, ev.Version),
			PyIdent: pyIdent(ev.Name, ev.Version),
			Wire:    fmt.Sprintf("%s@%d", ev.Name, ev.Version),
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Wire < entries[j].Wire })
	return entries
}

// RenderGo emits the Go source for the constants in the given package. The
// emitted source defines one const per event plus an AllEventNames() helper
// returning the wire strings in deterministic order.
func RenderGo(pkg string, entries []Entry) ([]byte, error) {
	if pkg == "" {
		return nil, fmt.Errorf("constgen: empty Go package name")
	}
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by openevents generate constants. DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	width := identWidth(entries, func(e Entry) string { return e.GoIdent })
	fmt.Fprintln(&buf, "const (")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%-*s = %q\n", width, e.GoIdent, e.Wire)
	}
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// AllEventNames returns the canonical event-name strings in deterministic order.")
	fmt.Fprintln(&buf, "func AllEventNames() []string {")
	fmt.Fprintln(&buf, "\treturn []string{")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t\t%s,\n", e.GoIdent)
	}
	fmt.Fprintln(&buf, "\t}")
	fmt.Fprintln(&buf, "}")
	return buf.Bytes(), nil
}

// RenderPython emits the Python source for the constants plus an
// ALL_EVENT_NAMES tuple in deterministic order.
func RenderPython(entries []Entry) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintln(&buf, `"""Generated by openevents generate constants. DO NOT EDIT."""`)
	fmt.Fprintln(&buf)
	for _, e := range entries {
		fmt.Fprintf(&buf, "%s = %q\n", e.PyIdent, e.Wire)
	}
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "ALL_EVENT_NAMES: tuple[str, ...] = (")
	for _, e := range entries {
		fmt.Fprintf(&buf, "    %s,\n", e.PyIdent)
	}
	fmt.Fprintln(&buf, ")")
	return buf.Bytes(), nil
}

// goIdent maps "checkout.started", 1 → "CheckoutStartedV1".
func goIdent(name string, version int) string {
	parts := strings.Split(name, ".")
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(camelSegment(p))
	}
	fmt.Fprintf(&b, "V%d", version)
	return b.String()
}

// pyIdent maps "checkout.started", 1 → "CHECKOUT_STARTED_V1".
func pyIdent(name string, version int) string {
	parts := strings.Split(name, ".")
	pieces := make([]string, 0, len(parts)+1)
	for _, p := range parts {
		pieces = append(pieces, strings.ToUpper(strings.ReplaceAll(p, "-", "_")))
	}
	pieces = append(pieces, fmt.Sprintf("V%d", version))
	return strings.Join(pieces, "_")
}

func camelSegment(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	subs := strings.Split(s, "_")
	var b strings.Builder
	for _, sub := range subs {
		if sub == "" {
			continue
		}
		b.WriteString(strings.ToUpper(sub[:1]))
		b.WriteString(sub[1:])
	}
	return b.String()
}

func identWidth(entries []Entry, pick func(Entry) string) int {
	w := 0
	for _, e := range entries {
		if n := len(pick(e)); n > w {
			w = n
		}
	}
	return w
}
