"""Generated by openevents generate constants. DO NOT EDIT."""

CHECKOUT_COMPLETED_V1 = "checkout.completed@1"
CHECKOUT_STARTED_V1 = "checkout.started@1"
SEARCH_PERFORMED_V1 = "search.performed@1"

ALL_EVENT_NAMES: tuple[str, ...] = (
    CHECKOUT_COMPLETED_V1,
    CHECKOUT_STARTED_V1,
    SEARCH_PERFORMED_V1,
)
