// Code generated by openevents generate constants. DO NOT EDIT.

package eventmap

const (
	CheckoutCompletedV1 = "checkout.completed@1"
	CheckoutStartedV1   = "checkout.started@1"
	SearchPerformedV1   = "search.performed@1"
)

// AllEventNames returns the canonical event-name strings in deterministic order.
func AllEventNames() []string {
	return []string{
		CheckoutCompletedV1,
		CheckoutStartedV1,
		SearchPerformedV1,
	}
}
